### ISSUE TITLE
Integration of Podlove Web-Player (Feature request)

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#175]
It would be a great feature to implement the Podlove Web-Player into Serendipity:

https://github.com/podlove/podlove-web-player

**Comment by garvinhicking** [comment]
Ok, I am giving up on this player. I don't understand how it really works.

I have managed to patch up the player so that the podlove stub is used (that's pretty easy), but it seems that podlove requires you to have a static .html file with the actual MP3 file to play as an external request. 

This really sucks, because the way I read the documentation is that it wants to to use a <audio> element as a stub (the src files will be disregarded) and another HTTP request loads the frame content, but that requested file needs to have the proper <audio> tags. So we would need to make a whole roundtrip just to specify the player files to show, which is available in first place.

On top of that, chapter support requires you to add chapter marks etc. yourself, so there would need to be an interface for that.

All in all, this is so much work also manually, I suggest you to do the following to use podlove:

1. Edit your template, add the <script> tag to the podlove moderator.min.js file

2. Create a directory like templates/podlove/player1.html

3. Manually edit that file and format it along the lines of http://sourcerer.org/blog/?podcast=lnp131-internet-der-kurzen-wege&podloveEmbed=1 so that you add chapter marks, metadata etc. in the file.

4. In your blog posting, post this HTML5 audio snippet:

````
<audio controls=1 preload="none" id="audio1" data-podlove-web-player-source="/themes/podlove/player1.html">
    <source src="uploads/your-mp3file.mp3" type="audio/mpeg" />
</audio>
<script>
  jQuery('#audio1').podlovewebplayer();
</script>
````

5. Now for each and every new mp3 audio file / blog post, create a new file like "player2.html", "player3.html" and so on (of course you can use any filename you like). Also make sure to adjust the <audio> tag for a unique "audio1", "audio2", ... name so that multiple players can be on the same page.


Regards,
Garvin

**Comment by garvinhicking** [comment]
Great, now even github ate half of my response what the actual heck....

**Comment by yellowled** [comment]
I brought it back. Magic! :)

**Comment by yellowled** [comment]
Well, If even @garvinhicking is giving up, I'd suggest that we close this issue (I'll leave that up to @ddeimeke, though) and open up a forum discussion about how to improve the existing podcasting plugin. There are other players available, we don't *have* to port podlove. I'm not even sure we are really aware what it is that podcasters *need* in s9y/that plugin.

Also, a very interesting topic for `#s9ycamp` (again, I know). I feel like this would be a really good way to add a unique selling point to s9y (without becoming a “podcast CMS”, of course).

**Comment by ddeimeke** [comment]
If you want to offer only one file type - either ogg or mp3 - you need any sort of plugin.

Safari does not support ogg and Firefox (plus Opera) does not support mp3.

Old, but still valid: https://dev.opera.com/articles/html5-audio-radio-player/

DeimHart - my former podcast - offered mp3 AND ogg files because of that, but in the end it is unnecessary work.

The situation may change in 2017 because of the mp3-patents running out.

I am ok with discussing this in the forums.

The podcasting plugin needs a lot of love and would be much easier to configure if we had any sort of media player.

**Comment by yellowled** [comment]
I'll start a discussion thread in the forums with your (brillant) starting points.
