### ISSUE TITLE
entity functions and double_encoding issues with ISO-8859-1

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#250]
follow-up from #236 

> We would need to find the places where we actually do double encoding, and fix those.

To sum this behaviour mentioned in #236:

None supported chars are stored as entities to database. eg `日本 and äöü and € β ♥` as `&#26085;&#26412; and äöü € and &#946; &#9829;`.

serendipity_printEntries() will now run htmlspecialchars() to $entry['title'], $entry['title_rdf'] and $entry['author'] but not to $entry['body'] etc. This is why $entry['body'] etc works, but the title will be double_encoded to `&amp;#26085;&amp;#26412; and äöü € and &amp;#946; &amp;#9829;` (each `&` to `&amp;`), while htmlspecialchars does not care (if you don't advice it) and encodes every found `&` again.

This happens to staticpages too, We can now say "_don't use such chars then..._" or find a solution to not let it happen like this and unescape first before escape, or just by setting double_encoding behaviour to false particularly or generally.

**Comment by ophian** [comment]
Happy New Year!

_I don't need this issue (see above) to talk to/with myself... :)_, but I do need a concerted action or at least a solution for staticpages dev to close v. 4.32 finally. (This and some other earlier changes bring up the need to update some already included staticpage template files, like in 2k11 and bulletproof. It would be nice to have them already included to the final 2.0 release.)

If we don't say to not touch this at all, I really think of using something like `$this->fixUTFEntity($entry['title'])` or `serendipity_specialchars($entry['title'], null, LANG_CHARSET, false);` for certain array parts like 'title', 'author', 'title_rdf', etc. (sp name, sp description, sp pagetitle, sp meta_*, etc), where this 2xencode issue can possibly happen. 

Since this also relates to certain array parts of serendipity entries, I would prefer a more general solution, located in core, without loosing security.

**Comment by garvinhicking** [comment]
Happy New Year!

This is a more complicated issue so I cannot respond timely to it. The route you describe in your first paragraph of the initial reply to me might not the way to go.

A proper fix is not to prevent encoding encoded chars a second time, but to not actually encode chars a second time.

Thus, when we do serendipity_specialchars in PHP to assign to $entry['title'] we need to check if this variable is really outputted in PHP. The problem would only occur if we use one variable to be both outputted in PHP *and* a Smarty Template. So for me, there are two ways to approach:

1. We change the .tpl files and remove the |escape modifier, because PHP took care of that already. Then we'd need to notify users of the files to fix possible local copies for them as well.

2. Instead of assigning $entry['title'] (which is "encoded") to the Smarty TPL, we make $entry['title'] NOT be passed to serendipity_specialchars, but use a $entry['_title'] variable to be passed. That makes $entry['title'] unsescaped, and be properly used in Smarty. In PHP we then need to change every occurence of where $entry['title'] was used to refer to $entry['_title'] instead.

If possible, to minimize possible oversights and breakage, I would like to use variant #1 for as much occurrences as possible.

Whenever we find a variable that is passed to serendipity_specialchars but *NOT* being used in PHP, we would simply remove the serendipity_specialchars() call and make sure that each reference to that variable inside a .tpl file actually uses the "escape" modifier.

Regards,
Garvin

**Comment by yellowled** [comment]
I literally have no idea what this is about, but a happy new year to you, too. :o)

**Comment by ophian** [comment]
Don't click on #1, which is a happy new year too, but is totally unrelated ;-)

Garvin, variant (1) is a self-evidence and should be already done ("hopefully" nearly) everywhere, since doing entity encodings twice via 2 compiler engines, is bad, and which would end up in a "quadrofonic encoding" in the cases I'm talking about:

This are these special cases, where we have other db table fields than body to save values encoded, eg as `&#26085;&#26412;`, since not being supported by the ISO charset. If that runs through "normal" htmspecialchars on output, which we wisely don't do with body content, we get it double encoded to `&amp;#26085;&amp;#26412;`. 
(Imagine an asian user with ISO charset inserting its asian-chared name as author, or similar to title)

This is what the double_encode parameter is for, IMHO, which ensures `&` not to be encoded again, if it is a `&amp;`already. (BTW same as `fixUTF9entity()` does).

Or did I not get your real mean...?

**Comment by ophian** [comment]
(edited!) ...ensures `&` not to be encoded again, if it is a `&amp;` or `&#$1;` or part of any htmlentity already.

**Comment by garvinhicking** [comment]
Hm. I'd say that those chars should really not be used then; if someone asian would need the chars they should use a UTF-8-Blog.

Just to use char encoding prevention that could possibly result in security issues for those installs is IMO not the proper way to go. We shouldnt add a layer of extra complexity to deal with that IMO.

Since an issue like that hasn't been reported, I'd not put too much effort into something that can be averted by using UTF-8...

**Comment by ophian** [comment]
> Hm. I'd say that those chars should really not be used then; if someone asian would need the chars they should use a UTF-8-Blog.

Simply the best, yes! :smile: I came into talk with that, since you claimed Serendipity being widely used in Asia with native or ISO charsets and this being a unique characteristic. Since I could not play around with native charset other than german, I used ISO to test this. I am quite sure there are a lot of these users having native keyboards and write for their own lang only, which includes titles, names etc.



> Just to use char encoding prevention that could possibly result in security issues for those installs is IMO not the proper way to go.

This is still a question for me: how this could be exploited?

**Comment by garvinhicking** [comment]
The ISO charsets were german ones... Asians would use this koi8r charset.... So usually if someone uses a local charset he uses local characters and not pnes that aren't available. For such content UTF-8 was created, so I really think we'd be fine with that ;)

I don't have specific examples for the exploiting, it's more a gut feeling and I would rather inspect other issues ;-)

**Comment by ophian** [comment]
Yeah, I know! At this point I'll close this issue and will see how to handle this with my SP DEV, which no one else but me uses anyway.

**Comment by garvinhicking** [comment]
Well if it's really an issue that you experience, you could always add a config option to allow preventing double escaping, set to false by default...?
