### ISSUE TITLE
PHP 5.6 - deprecated function within PEAR

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#256]
Updated PHP from 5.3 to 5.6 and now i get a message like following, when i publish an article.

> sitemap.xml:
> Sitemap Update an www.google.com gemeldet.
> 
> Deprecated: Non-static method PEAR::getStaticProperty() should not be called statically, assuming $this from incompatible context in /var/www/virtual/bd/bernd.distler.ws/bundled-libs/PEAR.php on line 847
> HTTP_Request Object ( [_url] => Net_URL Object ...

**Comment by stevleibelt** [comment]
So my issue [my](https://github.com/s9y/additional_plugins/issues/41) is the same?
If so, you can close it (but please, answere the questions inside). 

@yellowled 
Do you need support on that? All I can offer is going through the [plugins](https://github.com/s9y/additional_plugins) and add "static" to the needed method calls.

**Comment by yellowled** [comment]
I'm not entirely sure what's the proposed course of action here, I'm just the frontend dude labelling issues. :)

**Comment by stevleibelt** [comment]
@yellowled 
ok, thanks for the quick reply :-).
Lets see what a backend person will write about it.

**Comment by garvinhicking** [comment]
Yes, we could happily need help for that. 

Currently we bundled PEAR.php with a few minor additions so that s9y can properly work; however that old PEAR.php did not have static keywords, then we patched it, then we removed it, so the current state is not so really clear to me. We have a few PEAR dependencies (HTTP_Request) that would need to properly work with that.

Only recently PHP began to throw actual errors (instead of warnings) with those issues,so we have a knid of "legacy" problem here, and we can't easily update everything since PEAR is quite unmainted in parts and libraries that we use.

So it's all a possible mess, and I believe we'll need to find every function that is static, and put the static keyword in there. But we also need to make sure a function is ONLY used statically, because if we give it a static keywords and other places use $this->... to call the function that would throw a different fatal error and could make things worse.

**Comment by ophian** [comment]
>     Deprecated: Non-static method PEAR::getStaticProperty() should not be called statically, assuming $this from incompatible context in /var/www/virtual/bd/bernd.distler.ws/bundled-libs/PEAR.php on line 847

@bauigel This should go away if you try with this 9fbb248 commit

**Comment by bauigel** [comment]
> @bauigel This should go away if you try with this 9fbb248 commit

Thank you, error is gone when sending an article. Maybe we should leave this issue open, don't know if other parts/plugins could even make problems?

**Comment by yellowled** [comment]
If we were to consider “might”, we'd never close *any* issues.=

**Comment by ophian** [comment]
@bauigel I needed to fix this more, see d758e6b 

This can't be closed yet, since there is at least the non static raiseError call(s) in HTTP/Request.php left, which is/are not that easy to handle, I assume, like Garvin already stated.

**Comment by ophian** [comment]
@garvinhicking  please have a look into all these patches for PEAR
https://github.com/s9y/Serendipity/commits/2.0/bundled-libs/PEAR.php
The last two version updates for example changed back your `instanceof`  patch replacing the `is_a()` (which is PEAR default and no longer set deprecated by PHP) and about raiseError(), which is used by Net/Socket too, which might need an update too, ie last fix for 1.0.14 in Mai'13 was `- Fix connecting when host is specified with protocol prefix e.g. ssl://`) and the necessary update for bundled-libs/.current_version, etc. I am not able to test these ssl trackback issues deeply to really understand what is going wrong.

**Comment by garvinhicking** [comment]
Hm, to me the current patches seem quite well, I think that should work like it is now, yes? Thanks!

**Comment by ophian** [comment]
What about http://board.s9y.org/viewtopic.php?f=10&t=20191&start=15#p10441335 ?
(I cannot test this)

**Comment by yellowled** [comment]
@garvinhicking and @onli said in the devtalk it works for them with https://, so we should investigate this further if/when it comes up again with a more precise bug report.
