### ISSUE TITLE
$entry.ep_is_sticky in dashboard entries

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#261]
OK, in dashboard overview.inc.tpl this should be {if $entry.properties.ep_is_sticky}, but it does not make real sense having it here at all. It will only work for drafts or futures though... and then these grey notices get somehow crouded.

BUG! And, If set as a draft, publishing will remove the ep_is_stick properties flag, since this action will only update the entries table, flushing but not updating serendipity_entryproperties. We have to make sure a dashboard publish entry action does not touch serendipity_entryproperties entries! Any ideas?

(Copied from #260 to seperate issues.)

**Comment by garvinhicking** [comment]
Ok, @ophian that indeed was a nasty bug.

It seems to be in for forever though, I'm quite surprised. I thought it was addressed at some point because many plugins have a line:

´´´
$serendipity['POST']['properties']['fake'] = 'fake';
´´´

in them so that entryproperties would not be removed, but this actually changed nothing it seemed.

I've just addressed this in my commit, so that entryproperties will not remove values, if no POST var was actually set with properties. This fixes resetting entryproperties for the cases where serendipity_updertEntry() is used like in the dashboard.

HOWEVER I'm a bit afraid this could lead to sideeffects, so I'll leave this issue open and maybe you other guys can check it out as well. @onli what do you think?

**Comment by ophian** [comment]
Well, its not really a nasty one, since it only happens when using dashboard entry publish, which uses because serendipity_updertEntry. 

This all is a follow up from https://github.com/s9y/Serendipity/issues/160. I fixed the isdraft state and timestamp, @mattsches added some others https://github.com/s9y/Serendipity/commit/800255960311267879f41f8b8b7c9bc145fb3887 because of event plugin hooks.

I am not sure your commit adresses that all and has no other sideeffects. Its all here https://github.com/s9y/Serendipity/blob/2.0/include/functions_entries.inc.php#L1415.

We could end up checking all necessary $entry vars to $_entry as well **or** even better, don't use `$res = serendipity_db_update('entries', array('id' => $entry['id']), $entry);` and use a simple UPDATE SET to update the isdraft flag singulary. This would avoid touching other fields and tables. Then we could reset all these helpers for publishing a draft via dashboard. The more I think about it, I would prefer a simplicity like that.

And that all, if we are really sure to keep the publish draft submit on dashboard at all, see #262. 

Or we could check to show the submit button only on entries, which do not have properties. For the latters a note could be added: "Publish via edit only", or something...

**Comment by garvinhicking** [comment]
I think you are mixing this with something else.

My commit affects the serendipity_event_entryproperties plugin because this is the one that deletes all entryproperties when serendipity_updertEntry() is called, and properties are not submited through $serendipity['POST']['properties'].

This is the case in these plugins, in addition to the overview.inc.php updertEntry call:

````
./serendipity_event_freetag/serendipity_event_freetag.php
./serendipity_event_trackback/serendipity_event_trackback.php
./serendipity_event_aggregator/serendipity_event_aggregator.php
./serendipity_event_popfetcher/serendipity_event_popfetcher.php
./serendipity_event_picasa/serendipity_event_picasa.php
./serendipity_event_imageselectorplus/serendipity_event_imageselectorplus.php
./serendipity_event_xmlrpc/serendipity_xmlrpc.inc.php
./serendipity_event_phoneblogz/serendipity_event_phoneblogz.php
./serendipity_event_autosave/serendipity_event_autosave.php
./serendipity_event_suggest/serendipity_event_suggest.php
````

This is not related to any metadata of serendipity_entries. Only entryproperties, like the actual bug is about...

**Comment by ophian** [comment]
Could well be I am misled... all I wanted to say is, avoid using serendipity_updertEntry()  to publish a dashboard entry draft... which only needs to change the flag (and the timestamp perhaps, see discussion). Isn't that better?

**Comment by garvinhicking** [comment]
It's better to use a central API for that, even if we only change a small thing.

**Comment by ophian** [comment]
I did not get you fixed a bug bigger than the dashboard publish issue... that indeed was a nasty one!
And it works! Do we now need to keep the title body extended author backup https://github.com/s9y/Serendipity/commit/800255960311267879f41f8b8b7c9bc145fb3887 ?

**Comment by garvinhicking** [comment]
Closed, should be done with the fix. The other thing about timestamp is discussed seperately.
