### ISSUE TITLE
care for -webkit-linear-gradient but not -moz...?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#270]
@yellowled Is there an explizit reason why you took care for older Webkit Engines, but not for older Mozillas Engines in gradiants etc? Example:
```css
background-image: -webkit-linear-gradient(#fff, #ddd);
background-image: linear-gradient(#fff, #ddd);
```

**Comment by yellowled** [comment]
Yes. http://caniuse.com/#feat=css-gradients (Click on “Show all” to see older versions.)

Both Chrome and Firefox support unprefixed linear gradients way back, but Safari, iOS Safari and Android Webkit don't. Those are browsers we can't assume to be updated frequently because their version is tied to the OS they run on. We can safely assume that most Chrome and Firefox users will be on fairly recent versions (and thus save quite an amount of CSS code because we use linear gradients a lot).

**Comment by ophian** [comment]
Yeah, I see Mozilla started to support the standard with FF 16, Chrome with 26.
Yes, that seems to be acceptable for moz. I fell over this yesterday and just wanted to make sure you did not forget it.

**Comment by yellowled** [comment]
You can safely assume that I double-checked every vendor prefix in the last CSS cleanup (although I don't remember when I did that).
