### ISSUE TITLE
failing serendipity_editor.js error, if no freetags installed 

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#272]
I just updated an official blog by the autoupgrade, which went through successfully under a minute and was about to throw a happy "Hooray!". But then I enabled the wysiwyg editor and got back to the backends entry form and got a Firefox stopping js error, yelling that $source was not defined at `var tagged = $source.split(',');`. 
I already fixed this with b0e1688  `fix failing error if no freetags installed` (be9d45e).

I think we also need to change the entryform to not show up the "Tags" line, if the plugin is not installed or the tags are empty.
![emptytags](https://cloud.githubusercontent.com/assets/1105372/5872995/e6bda216-a2f1-11e4-9c2a-d651dcdea92e.png)

**Comment by yellowled** [comment]
Yes, I missed that. Good catch.

**Comment by garvinhicking** [comment]
I just committed a change to 2k11/admin/entries.tpl to add the same IF-clause around it.

However, won't the jquery thing like $('freetag').val() fail because $('freetag') is not existing? Or does jquery then gracefully still execute .val() on that object without an error? Have no time to check that.

Maybe someone can check whether the javascript now still works properly with freetag being disabled and give feedback so that I can re-upload the 2.0 release?

**Comment by yellowled** [comment]
I will test this with a git snapshot shortly. Need some time, though.

**Comment by ophian** [comment]
No other error - works fine with that entries tpl patch! ....well I did not remove my serendipity editor,js patch though.

**Comment by garvinhicking** [comment]
sure, i believe the JS patch needs to stay and not be removed!

**Comment by yellowled** [comment]
You are … quick. Thanks. :)

**Comment by ophian** [comment]
> However, won't the jquery thing like $('freetag').val() fail because $('freetag') is not existing? Or does jquery then gracefully still execute .val() on that object without an error?

I think it will always fail if you actually in follow want to do something with that var. This is why it failed at  var tagged = $source.split(',');` and not before.
