### ISSUE TITLE
backend user.css?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#280]
What was the last decision about (not?) using a backend user.css? (I don't remember..)

**Comment by yellowled** [comment]
I think the decision was that we *need* to have a backend user.css as well as a backend user.js (maybe? not clear on that) to make it easy for users to customize the backend without having to write a new backend theme (i.e. for people that want the backend `font-size` smaller or whatever).

I never liked the idea, but I'll bow down to if it's consensus that we *need* to have this.

I don't know if this is already implemented.

**Comment by ophian** [comment]
> I don't know if this is already implemented.

Nor me. If we get this clear we can label this to 2.x.0 I assume.

**Comment by yellowled** [comment]
Pretty sure it's not implemented yet.

`grep -rl user.css *` on `master` only gives back references to 2k11 (frontend only) and BP.

**Comment by bauigel** [comment]
I would like to see this for a future version, because i missed it sometimes already.

**Comment by yellowled** [comment]
Looking at `serendipity.css.php` with the eyes of a not-so-skilled PHP coder, this should actually be a)  simple and b) make it possible to have a user.css in *all* frontend themes without the theme even having to include it.

If I understand `serendipity.css.php` correctly, it generates CSS for backend and frontend by combining a few components, which are similar for backend and frontend:

* contents of the “global” `style_fallback.css`
* contents of a hook (`css` or `css_backend`)
* contents of a stylesheet file (`style.css` or `admin/style.css`)

Shouldn't it be possible to just add another step? “Add contents of `user.css` or `admin/user.css` if it exists, otherwise skip”? We'd have to remove the `user.css` references in 2k11 and BP (both frontend only), but that's not an issue since both are part of the core. As far as I see, the only theme in `additional_themes` using a `user.css` is `photo`, which requires 2.0 anyway. I guess we'd have to adjust the required version for `photo` to the one that includes this then.

Or am I missing something here?

**Comment by garvinhicking** [comment]
Yes, this should work by adding:

`````
$out .= serendipity_printStylesheet(
         serendipity_getTemplateFile('user.css', 'serendipityPath'),
         serendipity_getTemplateFile('user.css', '')
);
`````

just before the hook_event($css_hook, $out) line. I believe this would only make trouble if an existing theme bundled a user.css that would now get auto-loaded. And it costs some extra performance to perform a looking and search for user.css in all those directories... but I'd say this is neglectible.

Do you want to try this patch and commit it, and maybe @ophian or @onli have thoughts about this?

**Comment by onli** [comment]
I like the idea, and having some css lines doubled in case of not updated themes should not really hurt. 

Only addition: We'd have to test whether that code really work in backend and frontend to only select the relevant user.css, also in the preview.

**Comment by yellowled** [comment]
> I believe this would only make trouble if an existing theme bundled a user.css that would now get auto-loaded.

As I said earlier: “We'd have to remove the user.css references in 2k11 and BP (both frontend only), but that's not an issue since both are part of the core.”

>  And it costs some extra performance to perform a looking and search for user.css in all those directories... but I'd say this is neglectible.

Saves us an HTTP request in loading the user.css, though.

@onli What about `photo`? I think we'd have to increment the required version on that, right?

**Comment by onli** [comment]
> @onli What about photo? I think we'd have to increment the required version on that, right?

Why exactly? :)

**Comment by yellowled** [comment]
Because it includes a `user.css` which then would be included by the core and by the theme. (Yes, I saw it's optional in `photo`, but if that option is used, it would be included twice.) We could also remove the `user.css` references in `index.tpl` and the theme option for it.

Or, you know, we could just move `photo` to the core.

**Comment by garvinhicking** [comment]
We could circumvent this and make themes use a filename like "userstyle.css" or "style_user.css"? That shouldn't be used by other themes yet...?

**Comment by garvinhicking** [comment]
to get this off the ground I just committed a proposal to master & 2.0 to work with

**Comment by garvinhicking** [comment]
OTOH of course, using "user.css" will make sure that BP/2k11 will automatically pick up on that file...?!

**Comment by onli** [comment]
> Because it includes a user.css which then would be included by the core and by the theme. 

Ah, that's not too bad for the time being. I'd just keep it like that and later remove the option, and then indeed bump the requirement. Thanks for pointing that out.

> Or, you know, we could just move photo to the core.

Well, that would double where it is, as it is already on spartacus and this version would have to either be removed or be patched anyway. Not worth it imho (I'd like to have it in the core, but bundling the spartacus version when making the release archive or something like that).

**Comment by onli** [comment]
@garvinhicking: I think user.css would be better, just automating what is already there.

**Comment by garvinhicking** [comment]
Yeah, it's better, and the photo-theme suggestion should also be fine; it shouldn't hurt if the CSS is loaded twice, I believe, and can be removed later on. Committed a change.

**Comment by yellowled** [comment]
I'll test this in a few, just to make it clear:

* /templates/<THEME>/user.css will be the frontend user.css
* /templates/<THEME>/admin/user.css will be the backend user.css

correct?

**Comment by garvinhicking** [comment]
Yeah exactly. There might be some border cases (most nobably the dreaded infamous "preview iframe"), where possibly the frontend user.css could be loaded where in reality we would need the backend user.css or vice versa. Basically the same edge cases that hit us when we separated backend from frontend themes.

**Comment by yellowled** [comment]
* `/templates/2k11/admin/user.css` works
* `/templates/2k11/user.css` works

I assume it will work with BP just fine as well, so I'll go ahead and remove the `user.css` from index.tpl and theme options for BP, 2k11 and Next.

**Comment by yellowled** [comment]
>  the frontend user.css could be loaded where in reality we would need the backend user.css or vice versa

I'm not 100% sure, but I think that's buggy at the moment anyway. I was gonna investigate that a little more and make an issue for it later anyway.

**Comment by garvinhicking** [comment]
Maybe it's worth thinking about emitting an "info" notice on the theme 
page which says "Create a user.css if you want to override any style". 
Or maybe even put such a notice into the style.css file, where people 
usually start looking to edit a file?!

(Then again, we would need to put it into every style.css file...?)

**Comment by yellowled** [comment]
Yeah, I was thinking about that, too. It does not really change for people who already use it, but new users or people switching to these themes might need that.

**Comment by yellowled** [comment]
I guess I'll just add it as a `custom` theme option.

**Comment by yellowled** [comment]
Done.

Again, the diff is larger than expected. :( I can only assume that those files that have a larger diff had the wrong encoding before, my setup for encoding in the editor should be fine *and* I double-checked that I saved every file with the proper encoding …

**Comment by yellowled** [comment]
> it shouldn't hurt if the CSS is loaded twice

It does not hurt from a CSS point of view, it's just duplicate CSS. Meaning it won't look weird.

From a performance point of view, it's an unnecessary HTTP request (which can easily be adjusted by deactivating the theme option to incude it). I would still remove it for future users.

**Comment by yellowled** [comment]
I assume we can close this. Backend and frontend `user.css` through  `serendipity.css.php` works, theme options of core themes that use a `user.css` have been adapted.
