### ISSUE TITLE
generic backend content margin starter for plugin?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#293]
Do we have a generic div class "header" for backend plugin content, or shall we all use backend h2 for the right margin-top: 1.5em? (Some Plugins do not emit some h2 capable content.)

**Comment by yellowled** [comment]
If possible, a backend section should *always* start with a `<h2>` element (in order to create a meaningful heading hierarchy). If there is no proper lang constant for a backend section heading yet, please create one. If for some reason (I can not think of one) both is not possible, it should at least use an element that also has a `margin-top: 1.5em;` (for visual reasons). 

Please stop creating GitHub issues to ask questions, that is not what GitHub issues are for.

**Comment by ophian** [comment]
Well then, do it youself! Thanks.
https://github.com/s9y/additional_plugins/tree/master/serendipity_event_userprofiles
