### ISSUE TITLE
Backend msg styles in entry preview iframe

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#294]
For some weird reason, only *some* of the backend CSS styles for messages are applied within the entry preview `iframe` – the `icon-*` classes work (the icons are there), but the `.msg_*` classes don't (messages are not displayed in proper colors.

Forum reference: http://board.s9y.org/viewtopic.php?p=10441878#p10441878

**Comment by donchambers** [comment]
I don't see the admin/backend stylesheet loading here.  Why would you want backend/admin styles to a frontend preview? Loading the admin stylesheet for an entry preview runs the risk of introducing styles that override or otherwise conflict with the frontend.  The issue we were discussing was for success or errors - if wanted in preview, probably best to add those styles to the theme's frontend stylesleet.

**Comment by donchambers** [comment]
Could also use .serendipity_msg_important or serendipity_msg_notice which are in the fallback stylesheet.

**Comment by yellowled** [comment]
> I don't see the admin/backend stylesheet loading here.

Nevermind, I'm dumb. I tested this with a theme which has the exact same icons and message classes in the frontend, no wonder they worked there.

> The issue we were discussing was for success or errors - if wanted in preview, probably best to add those styles to the theme's frontend stylesleet.

But then you would have to have backend classes in the frontend theme. And since the backend and frontend themes can now be chosen independently in the backend, that doesn't make much sense. (Which does not bring us closer to a solution.)

I will close this issue here. This clearly needs more discussion in the forums to find a possible fix, and I misformulated the issue in the first place.
