### ISSUE TITLE
Search results not found on pages > 1

### ISSUE THREAD

**Issue by donchambers** [s9y/Serendipity#309]
Both Don and YL have experienced this bug.   Search term may return more results than what s9y is configured to display per page.  When navigating to next page, no further results are shown.  
For example, Don's blog template demo here: http://www.optional-necessity.com/demo/cleanblog/

Search for the term "lorem". It will correctly say: "Your search for lorem returned 4 results:"  s9y is configured to only show 3 entries per page, so you get the first 3 results and a next page link. But when you go to the next page for the 4th result, you get: "No Entries Found for Query lorem".

Search for term "serendipity" on YL's devblog: http://s9y.netzgestaltung.net/.  First 5 results are shown on first page.  Page 2 also shows no entries found.

s9y forum reference:  http://board.s9y.org/viewtopic.php?f=16&t=20281&p=10442187#p10442187

**Comment by garvinhicking** [comment]
Can you please edit include/functions_entries.inc.php at around line 860 (using current 2.1 master branch) and modify:

    $search =& serendipity_db_query($querystring);

to

    $search =& serendipity_db_query($querystring);
    echo $querystring;

This would show the SQL used for the second page SQL. Maybe there's an SQL error in it for pagination LIMIT / OFFSET.

**Comment by donchambers** [comment]
I did.  Output is at the bottom of the page when you search.

**Comment by onli** [comment]
(MATCH(title,body,extended) AGAINST('lorem*' IN BOOLEAN MODE))

first page versus

    (MATCH(title,body,extended) AGAINST('lorem'))

second page. That looks like the code to have more results when only having three?

**Comment by garvinhicking** [comment]
Yeah, exactly. Search is executed with "*" in the boolean mode again, but only on the first page.

I must admit the whole code block is a bit too complex for me. I believe @ophian initially contributed this, right? Do you see a possible solution?

At least, this will only happen in a very specific scenario where a searchword is not properly found in the database and a substitute query is executed. That substitute query was never meant to deliver much more than one page of results, so maybe we would need to restrict the amount of found entries for such queries to $serendipity['fetchLimit']?!

**Comment by donchambers** [comment]
@garvinhicking - what do you mean "this will only happen in a very specific scenario where a searchword is not properly found in the database and a substitute query is executed"?  How does that apply to this situation?  Are you saying the search term in my example "lorem" is not found in the database?

**Comment by garvinhicking** [comment]
Actually your lorem is found too often in the database, and thus mysql filters the results out due to a reaches threahhold. If you had a larger pool of entries where lorem would not exist, it would return the results without needing to "fall back" to a *-Query.

The fallback query will lead to trouble if there are more entries found than your fetchLimit, but less than 4, that's what I meant with "specific scenario". 

This scenario actually existed for a longer time (s9y 1.6 or 1.7 I beleieve?) but I don't really know how to easily proceed. Maybe if when we change to the fallback query we need to pass along the extended search parameter to the footer/pagination links (rewite the searchTerm-GET var), but that could maybe lead to more trouble than it solves. Not sure...

**Comment by onli** [comment]
I added some time ago code to the search function to add a `*` to the search term if less than 4 results are found. So, lorem is in the database, but exactly often enough to trigger the bug.

**Comment by ophian** [comment]
> I believe @ophian initially contributed this, right? Do you see a possible solution?

No. I had initially nothing to do with the search function(s). I have contributed some bugfixes, not more.
(No, not really. I'd say: _Don't touch_ :smile: )

This all is about the 50% mysql search term limitation, as such, it is effectively treated as a "stopword. "Please read: http://dev.mysql.com/doc/refman/5.0/en/fulltext-natural-language.html
The more rare a searchterm is, the more it is rated and weighted by the relevance of rows. Such a technique works best with larger database collections and really not to well on test installations with some few entries only.

And never use Serendipity or S9y in your search terms, since you will get unexpected results as `serendipity` is a name in class names quite often, eg image tags etc.

**Comment by yellowled** [comment]
> Such a technique works best with larger database collections and really not to well on test installations with some few entries only.

One good proof for this is actually that we haven't gotten any bug reports on this other than from people who use such test installations. Then again, nobody really uses their own search form, and visitors usually don't report such things …

But it's true, I can for example **not** reproduce it with the German word “Bild” in my dev blog. That works just fine, even on the second results page. (You're also right that it is hard to even find proper search terms in such test blogs.)

**Comment by mattsches** [comment]
>And never use Serendipity or S9y in your search terms, since you will get unexpected results as serendipity is a name in class names quite often, eg image tags etc.

Also, don't search for the term `plugin` because then you will end up with an empty page.

I think, it's the check for `$p == 1` in https://github.com/s9y/Serendipity/blob/master/include/functions_entries.inc.php#L882 that's causing the trouble, but I wil have to do further testing. I removed the check (leaving all the others in there), and it seems to work fine. Not sure why it's been there in the first place, because limit and offset should be enough?

**Comment by onli** [comment]
> I think, it's the check for $p == 1

I think you are right. It is from this commit: https://github.com/s9y/Serendipity/commit/51208e0f726cfc3a7b65360be6a58a5fcd1c3968#diff-cbbd600f627a5af39c73092fbc3fbf46 and seems to be based on http://board.s9y.org/viewtopic.php?p=10420249#p10420249. Does the original bug not reappear without that parameter?

**Comment by donchambers** [comment]
I removed the $p == 1, leaving this behind:
````
if (strpos($term, '*') === false && $serendipity['dbType'] != 'sqlite' && $serendipity['dbType'] != 'sqlite3' && $serendipity['dbType'] != 'pdo-sqlite' && $serendipity['dbType'] != 'sqlite3oo') {
````

..and as @mattsches said, it seems to be working fine.

**Comment by yellowled** [comment]
Works for me with 75397c7. @donchambers Can you check out the latest `master` and close this issue if it works for you as well?

**Comment by yellowled** [comment]
@onli Remember to `cherry-pick` 75397c7 to `2.0`?

**Comment by donchambers** [comment]
Also works for me.
