### ISSUE TITLE
improve spartacus.s9y.org theme section

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#314]
- [x] Include larger thumbnails (preview_fullsize)
- [x] Make blog.s9y.org use templatechooser event plugin (make sure that it store cookie/session only temporary)
- [x] Let themes link to blog.s9y.org with that specific template preselected
- [x] Make backend theme section also link to blog.s9y.org as preview possibility
- [x] Make templatechooser plugin be able to read "blacklist.txt" file and parse it

**Comment by garvinhicking** [comment]
You can now see it like this:

http://blog.s9y.org/index.php?user_template=additional_themes/1024px
http://blog.s9y.org/index.php?user_template=Serendipity

Before we really implement this to the spartacus view however we might want to make sure that every plugin actually works on blog.s9y.org. We'll need to create a blacklist for themes that will not work, so that they are not selectable on blog.s9y.org.

(The theme selection is saved in a 30-days cookie. We will still need to adapt the plugin so that on blog.s9y.org it can be configured to only save it in the browser session. Else, if one theme fails, the blog will always fail for users and they can't acccess our blog).

Anybody volunteer for checking the available themes in the site? @donchambers @ddeimeke ? :)

**Comment by donchambers** [comment]
Sure - isn't there a dropdown for theme selection?

Has the blog always been in German?

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

The only thing that really stands out as German to me is the continue reading link, and the entry footer...

**Comment by yellowled** [comment]
(By ✔ I mean: I have looked at the theme's index page in blog.s9y.org using the URL above.)

✔ chocolate_fudge
✔ GreenMile
✔ Modern_World_s9y_port
✔ Sagittarius-A (although it does not work too well since it's a magazine theme which requires some specific settings and markup)

Errors:

* RoundedCorner has a syntax error in index.tpl

**Comment by yellowled** [comment]
> Has the blog always been in German?

What makes you think the blog is in German?

**Comment by bauigel** [comment]
2015-03-10 14:57 GMT+01:00 Matthias Mees <notifications@github.com>:

> Has the blog always been in German?
>
> What makes you think the blog is in German?
>

​Maybe: "Serendipity Camp 2015 and the near future of Serendipity"
vollständig lesen
<http://blog.s9y.org/archives/262-Serendipity-Camp-2015-and-the-near-future-of-Serendipity.html#extended>
​
Or: Geschrieben von Garvin Hicking
<http://blog.s9y.org/authors/3-Garvin-Hicking> in

**Comment by donchambers** [comment]
Yep

**Comment by yellowled** [comment]
> RoundedCorner has a syntax error in index.tpl

Just pushed a fix for that. Hope that's all there's to it.

✔ adaptation
✔ andreas00
✔ andreas06
✔ andreas08
✔ andreas09 (almost all the andreas themes do not use core nav, so they look a bit weird in the demo context because the nav items are empty)
✔ artistic
✔ axcur

Errors:

* barSinister3 throws some weird errors in the footer because it does a `$probelang` in `config.inc.php` but does not *have* lang files at all.

**Comment by yellowled** [comment]
Oh, okay. I did not notice that. I was testing themes and I usually only read the blog in RSS form. :) So no idea if the blog was not in German earlier.

**Comment by yellowled** [comment]
✔ bartleby
✔ bazooka
✔ be-nice (Did that always have a half-naked lady as a header img?! o_O)
✔ blogger_death
✔ blue-haze
✔ blue-iceberg (boy, that's an ugly one)
✔ brownpaper
✔ carl_blue
✔ carl_green
✔ ceejay01

Errors:

* bex-01 throws a lot of 404 errors because of images which are there in the GitHub repo. Permissions maybe?
* same als bex-01 for blix
* blue does not work at all – which does not surprise me because all there is in additional_themes/blue is a `preview_fullsize.jpg`. Not sure why.
* same as blue for carl_contest

**Comment by garvinhicking** [comment]
Don't know when that happened; possibly I changed my local interface to german and then saved the global configuration of the blog, which set the language to german there. Sorry for that! Fixed!

About the themes: They all come from additional_themes/XXX/ so any plugin that references its assets not via getFile but via templates/myname/XXX will not work on blog.s9y.org...

**Comment by donchambers** [comment]
✔ zenlike
✔ youngbutstrong (no continue reading link)
✔ xkur
✔ xhtml_mp - this is the mobile plugin.  Blacklist?
✔ wp-clone
✔ truth
✔ translucency
✔ toolbox

terrafirma fails to load "category.gif", which comes before the continue reading link

**Comment by yellowled** [comment]
✔ chromZv2
✔ codeschmiede
✔ coffee_bar
✔ connections
✔ costa-nature_theme
✔ dreisechzig
✔ earphone
✔ elitist-latte
✔ fifty50

* more themes that only have a `preview_fullsize.jpg` (I assume this is some kind of fallback mechanism for the backend theme preview): competition, contest, default, default-rtl
* I think we should blacklist default-php and default-xml since they're kind of proof of concept?
* freshy throws a `Smarty Compiler: Syntax error`; just pushed a fix for that.

**Comment by yellowled** [comment]
✔ gila_two
✔ glossy_white
✔ hemingway
✔ hipporatorium – it does look broken, but I don't think it is …
✔ jazzcafe
✔ joshua
✔ joshua_nino
✔ joshua_tree

* greenway has 404 images as well
* i3theme actually has a CSS bug (probably from the original theme) which will position *any* h1 absolutely, and since some of the entries on s9y.org have h1 in their entry content … well, let's just say it looks a tad messy :D
* only preview_fullsize.jpg: idea
* informativ looks very broken; not sure if it's just old, but this can't be intended o_O also uses a constant that no longer exists (`NAV_DEFAULT`?)
* iphone.app – I think that belongs to the mobile plugin as well, so it should be blacklisted

**Comment by donchambers** [comment]
✔ tabacco_s9y_07
✔ styled-bar

Square - throwing an error for a missing language file.  The theme does have a few configurable items, but they are all hard coded in English.  This is a theme by Dave Cummins.  He probably intended to create a language file, just never got around to it.  I will create the english language file, and if anyone else wants to translate it, be my guest.

**Comment by yellowled** [comment]
> He probably intended to create a language file, just never got around to it.

I *think* we may have added that `$probelang` check later. Not sure if it's safe to remove from `config.inc.php`, though.

**Comment by ddeimeke** [comment]
Sorry guys, you are much too fast for me.

**Comment by donchambers** [comment]
> I think we may have added that $probelang check later. Not sure if it's safe to remove from config.inc.php, though.

I'm fixing it.....  though I question my sanity for doing so!

**Comment by yellowled** [comment]
✔ kamouflage
✔ ladybird
✔ ladybug
✔ leaf
✔ mimbo (although it looks weird because obviously its options have not been customized)
✔ mo3 (same as mimbo, magazine tpl weirdness)
✔ morsel
✔ newfangled

* only preview_fullsize.jpg: kubrick, moz-modern, **all** the mt-* and mt3-* themes, newspaper

**Comment by yellowled** [comment]
> Sorry guys, you are much too fast for me.

No worries, Dirk. Need a break myself now. :)

I'm really wondering about these themes that only have a `preview_fullsize.jpg`, though. At least some of them have more files in the `2.0` branch of `additional_plugins`. Maybe @onli can shed some light on this since he seems to have worked in `additional_plugins/2.0` last? This might be an incomplete merge or a merge that still needs to be done …?

**Comment by donchambers** [comment]
> Square - throwing an error for a missing language file. 

I created the missing English language file, and modified the config accordingly.  @garvinhicking - you need to download the latest version.

**Comment by donchambers** [comment]
splat - blacklisted

**Comment by donchambers** [comment]
✔ softenedcells
✔ soccer2006
✔ slate-grey
✔ simpla
✔ Sagittarius-A (newspaper style, looks slightly weird due to lack of configuration)
✔ safety-yellow
✔ s9y_thin
✔ s9y_orange (h1 & h2 links in banner are display:none.  theme is mostly just a stylesheet)
✔ s9y_bluegrey

rubyx - same issue as square, missing language file, same config items as square so I'll add the english language file and modify config.

**Comment by onli** [comment]
> Maybe @onli can shed some light on this since he seems to have worked in additional_plugins/2.0

additional_themes - but no, I'm not aware of anything. If files are missing that is not intended, though I think that 2.0 never uses the old preview anyway.

**Comment by yellowled** [comment]
> If files are missing that is not intended, though I think that 2.0 never uses the old preview anyway.

Given the current state of the `additional_themes` repository, I would assume the following. It doesn't  matter who commited it, by the way. :)

* Some themes were moved from core to `additional_themes` because we wanted more recent themes in the core.
* For whatever reason (I don't know), `additional_themes` has a branch `2.0`.
* The themes that were moved as well as some core themes have a directory in `additional_themes` which in `master` only contains the `preview_fullsize.jpg`. Since this is the file referenced for the theme preview in the 2.0 backend, I assume this is some kind of fallback mechanism for Spartacus?
* The themes that are no longer in the core have *only* the `preview_fullsize.jpg` in `master`, but all theme files in `2.0`. I assume this was done to not “confuse” Spartacus for non-2.0 users?
* Because of this, all the themes that were moved to `additional_plugins` as well as the ones that are part of the core do not work in the new preview mechanism on blog.s9y.org. That's not an issue for the core themes, but for the rest of them.

I guess the only actual question here – not necessarily directed at you ;) – is: is there a good reason for having some theme files only in `additional_themes/2.0` or can we merge those to `additional_themes/master` now?

**Comment by donchambers** [comment]
✔ resy

Now on reflection, and once again it is missing a language file, which leads me to two questions.

1)  I'm thinking I would rather remove the reference to a language file, than continue writing them.  Anyone have a problem with that? 

2) I keep finding config items specified as this:
````
    array(
        'var'           => 'navlink1text',
        'title'         => 'Navlink #1 Text',
        'description'   => 'Enter the first navigation text',
        'type'          => 'string',
        'default'       => 'About',
    ),

````
"title" doesn't seem to work.  All my themes use "name", which does work.  Did "title" work at some point in the past, and not now in 2.0?  If it did before, but doesn't now, that functionality probably needs to be restored, or every theme that uses "title" has to be changed to "name".  I have already modified the themes square and rubyx to use "name".

**Comment by yellowled** [comment]
> I'm thinking I would rather remove the reference to a language file, than continue writing them.

That's what I meant [above](https://github.com/s9y/Serendipity/issues/314#issuecomment-78075032). Don't know if it's safe to remove.

> Did "title" work at some point in the past, and not now in 2.0?

I don't know.

**Comment by donchambers** [comment]
I'm pretty sure it is safe to remove the language file reference - I did it on one of my development installs without any ill effect.

It seems that reflection and barSinister3 are the only two remaining themes that specify a language file, but do not actually have one.  barSinister3 doesn't really need one, because the only thing defined in config.inc.php is a dateformat, so the reference there can be removed.  

Reflection is substantially similar to square and rubyx, so I will go ahead and create the english language file for it.

**Comment by yellowled** [comment]
@garvinhicking I changed the issue to have subissues so we can check progress better. Does blog.s9y.org pull these regularly so that we can check the “problematic” themes again?

@donchambers You already took care of barSinister3, right? Looks like it in the commit log. Thanks.

**Comment by onli** [comment]
> I guess the only actual question here – not necessarily directed at you ;) – is: is there a good reason for having some theme files only in additional_themes/2.0 or can we merge those to additional_themes/master now?

I think we can merge now. If I don't mix things up really bad right now, that branch was never intended by me to survive the 2.0 release.

**Comment by donchambers** [comment]
> You already took care of barSinister3, right? Looks like it in the commit log. Thanks.

Yes.

**Comment by garvinhicking** [comment]
Yeah it should be fetched every 15 minutes now. Forgot to make the cronjob executable.

**Comment by garvinhicking** [comment]
Who wants to put those 2.0 branch files to master? I can do it tonorrow afternoon if no one else steps in. :)

**Comment by yellowled** [comment]
First come, first merge. ;)

I'm pretty sure I'm going to be busy tomorrow. Whoever does the merge should probably also revise the `blacklist.txt` – I think “the not-sures” should work after the merge.

**Comment by donchambers** [comment]
✔  Powered
✔  plus9
✔ plain-vanilla
✔  pixel
✔  pink-lilies
✔  photo
✔  perun_red
✔  perun_blue
✔  party-brown
✔  one_true_layout
Newspaper : preview_fullsize.jpg only

That should be all of them now.

**Comment by yellowled** [comment]
> one_true_layout

That's still out there? Jeez.

Thanks again for testing all these. :)

**Comment by donchambers** [comment]
> Thanks again for testing all these. :)

It was painful in many instances.  Difficult to believe how ancient some of those themes are.  I question whether we should really be making some of the available any longer.  Some of them might look a tad better simply by making them wider.

**Comment by yellowled** [comment]
Honestly, if there was nothing else to consider, I would throw out almost all of them in a heartbeat. But unfortunately, it's not like we're swimming in better alternatives.

I doubt that it's worth the effort to give those old things a makeover, though. :)

**Comment by yellowled** [comment]
b7f82f should fix blix as well (I screwed up the reference in that commit.)

**Comment by yellowled** [comment]
And that should fix terrafirma.

**Comment by yellowled** [comment]
✔ blix
✔ terrafirma

Also removed the former core themes from the blacklist so we can test them now that they have been merged from `2.0`.

**Comment by yellowled** [comment]
✔ mod-modern
✔ mt-*
✔ mt3-*
✔ newspaper

**Comment by garvinhicking** [comment]
OK I changed the templatechooser plugin and the spartacus homepage template to view this (should be done with tomorrows update).

@yellowled I added a new <a class="demoURL> in the .template_preview div from templates.inc.tpl - this currently looks nasty, maybe you can properly align it?

**Comment by yellowled** [comment]
Kind of “first day post-vacation” busy, but I hope I'll find some time to check this later today.

**Comment by ophian** [comment]
Just to mention it ... Template "next" has a (2cd) search input field right to category sidebar container.

**Comment by yellowled** [comment]
Will add a fix for that as well.

Also, the s9y blog throws 404s for various lightbox CSS/JS files. Might need a little tweaking in the plugin config?

**Comment by garvinhicking** [comment]
The reason is that 1024 ie is in templates/additional_themes/1024px/ - that means the http path is not /templates/1024/.

Templates that contain hardcoded paths will thus not run and would need a getfile call instead of hard paths.

So this is nothing that can be changed in any plugin...

**Comment by ophian** [comment]
But the lightbox thing is plugin based, I think. Its not in next for example.

**Comment by yellowled** [comment]
The issue is that it references a lightbox in `/plugins/serendipity_event_lightbox/lightbox/` which (no longer, I assume) exists. There is no reference to these files in *any* theme in the core or in additional_plugins, so it has to come from the plugin.

**Comment by yellowled** [comment]
So

* Next now suppresses the quicksearch plugin in the sidebar
* I changed the theme demo link to a button. Yes, it is debatable whether the search loupe is a good icon for a preview link, but it is consistent with the icon for i.e. previewing comments, and a text button is way too long unless we want to go with just “Demo” for the button text. (Which would probably require another lang constant.)

**Comment by yellowled** [comment]
I have one final suggestion, but I don't know if it's possible – should we maybe add the demo link for core themes as well?

**Comment by garvinhicking** [comment]
We can't really, because those are not listed in spartacus, and there's 
no way to find out if a template is a core template or a custom-user 
generated/copied theme (for which demo links are not allowed to occur...)

**Comment by yellowled** [comment]
Bummer.

So, close the issue?

**Comment by garvinhicking** [comment]
(Closed. Feel free to reopen if anyone disagrees or has concerns)

**Comment by garvinhicking** [comment]
Hm I didn't know that the plugin lightbox was enabled on the s9y.org blog. Don't think we actually used this, so I disabled the plugin for now...
