### ISSUE TITLE
archiveSortStable breaks serendipity_plugin_history

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#321]
When archiveSortStable is set to true, serendipity_plugin_history will not work because getTotalEntries() returns i.e. "4" for the matching entries, but because the first page is used as the maximum page number, the actual number of entries for the LIMIT BY string gets negative, which results in a SQL error, which will halt the whole page.

Say you have 609 pages of entries (2436 entries), and the history plugin should show all entries written in the same month last year (which would yield 4 entries). Then the code in include/functions_entries.inc.php:

´´´
                if ($serendipity['GET']['page'] == $totalPages) {
                    $limit = serendipity_db_limit(0, $limit);
                } else if ($serendipity['GET']['page'] == $totalPages - 1) {
                    $limit = serendipity_db_limit($limit, ($totalEntries - (($totalPages -2) * $limit)) - $limit);
                } else {
                    $limit = serendipity_db_limit(($totalEntries - ($limit * $serendipity['GET']['page'])), $limit);
                }
´´´

would go to the last routing and calculate:

4 - (4*609), 4
-> SELECT * FROM BLA LIMIT -2432, 4

This seems because serendipity_printEntryFooter() actually sets $serendipity['GET']['page'] to $totalPages.

Now I never really got the whole StableArchive thing, so could you have a look at this @onli? :-)

(This will actually also possible affect all other plugins that are called after printEntryFooter, so any plugin that uses serendipity_fetchEntries()...)

**Comment by onli** [comment]
I can't reproduce this. While I see what you mean in the code - the hack with page=totalPages is not nice - it is not producing an error in my testblog, the plugin is working fine. 

If the error really still exists in current my master, my suggestion would be to fix that in the plugin. We could remove the limit in https://github.com/s9y/Serendipity/blob/eab43b12f5560364487484f8764642c8fd5dc1e6/plugins/serendipity_plugin_history/serendipity_plugin_history.php#L163 and instead reduce the array to `$max_entries` manually. I doubt that would have a negative performance impact on most configurations, since the plugin is seldom used, and there shouldn't be too many entries in a typical timeframe.

**Comment by garvinhicking** [comment]
I believe the problem will be in every plugin that uses serendipity_fetchEntries() in the sidebar, not only the history plugin.

I personally don't understand the stableArchiveSort, so I can't take on this issue at the moment...

The issue is present in the 2.0.1 release, how did you try to reproduce/test it? You must try it on a blog with at least a couple of pages, and the history plugin configured in a way that when is shows entires from a year ago, you also need entries from a year ago...?

**Comment by onli** [comment]
I tested it on a blog with 5 pages, 29 entries, 7 from a year ago. The plugin is configured to show entries from a year ago. Not enough entries?

Otherwise, it is on master, not the 2.0 branch.

**Comment by garvinhicking** [comment]
Ok let me try to produce it locally (I did that with the blog from Mari, the intiial reporter). When I am able to reproduce, I can provide a dump to properly test it with, and then let's go from there?

**Comment by onli** [comment]
Yes, that sounds good. Because right now I'm not convinced the bug report is correct :/

> I believe the problem will be in every plugin that uses serendipity_fetchEntries() in the sidebar, not only the history plugin.

I think (even if the bug report applies) it would only trigger when a limit is set. And that the only sidebar-plugin using that function in spartacus is serendipity_plugin_showentries…
But let's see if you can reproduce it, always better to fix it at the core.

**Comment by garvinhicking** [comment]
@onli 

Reproducible in 2.1-alpha1, quite easily with this mkentries.php script:

```
<?php
include 'serendipity_config.inc.php';

$increment = 86400;
$start     = mktime(0,0,0, 1, 1, 2014);
$end       = mktime(0,0,0, 12, 31, 2014);

serendipity_db_query("DELETE FROM {$serendipity['dbPrefix']}entries WHERE author = 'mkentries1'");
for($ts = $start; $ts <= $end; $ts+=$increment) {
  echo "Create entry on " . date('d.m.Y', $ts) . "<br />\n";
  
  echo serendipity_db_query("INSERT INTO {$serendipity['dbPrefix']}entries
    (title, timestamp, body, authorid, author, isdraft)
    VALUES
    ('Testentry on " . date('d.m.Y', $ts) . "', '" . $ts . "', 'Lorem ipsum.', 1, 'mkentries1', 'false')
  ");
}
```

This will create multiple entries, and then configure the history plugin like this:

https://www.dropbox.com/s/yjdfj663uaw3h82/Screenshot%202015-03-16%2010.37.42.png?dl=0

(Maybe this date/timerange is what was missing in your test scenario). Once that is done, the sidebar plugin will fatally crash due to the die() when stableEntries is enabled.

**Comment by onli** [comment]
Works as well.

![history](https://cloud.githubusercontent.com/assets/900380/6677121/5fd6972a-cc2d-11e4-9c4c-1ae81460eddc.jpg)

But I had to adapt your script, adding moderate_comments and allow_comments, because of a NOT NULL clause. Which brings me to the idea that this might be database related thing?

However, it always shows the same 5 entries. That is wanted, right? Because when disabling stable archive, it only shows something on the first page… is the plugin supposed to be aware of the time used in the archive?

**Comment by garvinhicking** [comment]
Could be that other DBs filter out negative limits. Using mysqli here with mysql 5.5 server...?

I must admit I don't remember if the history plugin only worked on the first page...

**Comment by onli** [comment]
> Using mysqli here with mysql 5.5 server...?

sqlite here. That might be the difference.

**Comment by garvinhicking** [comment]
I guess sqlite simply returns 0 as a limit if its negative.

Could you try with mysql? :)

**Comment by onli** [comment]
> Could you try with mysql? :)

I instead debugged the limit produced. That indeed looks wrong: `LIMIT -301, 5`. SQLite evidently just doesn't fail because of small stuff like that. Think I can try to further work on it like that.

**Comment by onli** [comment]
Ok. The problem lies with the logic in serendipity_totalEntries. There, we count the entries the current query will fetch. When normally browsing the blog, this will be the number of available entries. Here, it is already filtered by date, and thus less (in my test case, it was 4). Then, 

    $totalEntries - ($limit * $serendipity['GET']['page'])

will be negative, as `$page` does not correspond to the number of entries fetched, it is not a counter here.

I don't think that happens often, that should be the only plugin doing this. My solution would be to catch the negative limit, to wrap it in a `max(0)`:

  max(0, ($totalEntries - ($limit * $serendipity['GET']['page'])))

I push that to master, you test it with mysql?

**Comment by garvinhicking** [comment]
Ok, sounds good to me!
