### ISSUE TITLE
2.0.1 breaks icon-font?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#326]
I just updated a remote blog via autoupdate. Its all working fine, but the icons are missing. :? 
Is this reproducible? I do not see the reason for it until now...

**Comment by yellowled** [comment]
I don't have a quick way to reproduce the autoupdate. Anything in the dev tools console? 404s, other error messages?

**Comment by yellowled** [comment]
My blog, which was updated wgetting a 2.0.1 zip and copying it over manually does not have issues with the iconfonts, so what would/might the autoupdate do differently?

**Comment by ophian** [comment]
Its not a matter of the autoupdater, I assume. But I don't see an issue for it.

I have some other matters too. Like debug for https://github.com/s9y/Serendipity/blob/master/include/plugin_api.inc.php#L91 seems to be **not null**, so that https://github.com/s9y/Serendipity/blob/master/include/functions_smarty.inc.php#L1204 ff is dropping the line to serendipity_editor.js. Still no console errors or like.

**Comment by yellowled** [comment]
One bug per issue, please.

**Comment by yellowled** [comment]
You're not getting a `Cross-Origin Request Blocked` message, are you? http://board.s9y.org/viewtopic.php?p=10442113#p10442113

**Comment by yellowled** [comment]
Trying to reproduce it.

1. The dashboard in 2.0 emits not only the update message, but also a stray “Array” below it.
2. Apparently, that is because the autoupdate plugin was not installed (fresh installation), but it should still not appear or (better) emit a message like “Autoupdate plugin is not installed” or something in order to not confuse users.
3. The autoupdate process should probably adhere to the 2.0 backend CI better, just as a side note.
4. The autoupdate went through like a charm.
5. No issue whatsoever with icon fonts after the autoupdate.

I'm sorry, I can not reproduce this.

**Comment by ophian** [comment]
No nothing. Meanwhile I tested another installation with autoupdate. And it returned all fine! 
I close this, but it is still strange though.

**Comment by yellowled** [comment]
Also no community feedback on this (I asked on Twitter). Probably some Cache-FU specific to that installation or something?

**Comment by ophian** [comment]
> Probably some Cache-FU

Yeah I ran the autoupdater again and it returned all successfully. Thanks.
