### ISSUE TITLE
debug serendipity_smarty_show bis not null for editor.js

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#327]
2.0.1
Property debug for https://github.com/s9y/Serendipity/blob/master/include/plugin_api.inc.php#L91 seems to be **not null**, so that https://github.com/s9y/Serendipity/blob/master/include/functions_smarty.inc.php#L1204 ff is dropping the line to serendipity_editor.js.

**Comment by garvinhicking** [comment]
Sorry,I don't understand.

In which case exactly is what not null, what doe "dropping the line" mean? How to reproduce, what is intented behaviour, what happens?

**Comment by ophian** [comment]
intented
```
/* $Id$ */
/*
# Copyright (c) 2003-2005, Jannis Hermanns (on behalf the Serendipity Developer Team)
# All rights reserved.  See LICENSE file for licensing details
*/

(function(serendipity, $, undefined ) {
...
```
now
```
/* Dynamically fetched /var/www/yourPathtoBlog/html/templates/2k11/admin/serendipity_editor.js.tpl on 2015-03-13 12:20, called from: include/plugin_api.inc.php:external_plugin */
/* $Id$ */
/*
# Copyright (c) 2003-2005, Jannis Hermanns (on behalf the Serendipity Developer Team)
# All rights reserved.  See LICENSE file for licensing details
*/

(function(serendipity, $, undefined ) {
...
```
plugin_api Ln 91 ` echo serendipity_smarty_show('admin/serendipity_editor.js.tpl', null, 'JS', 'include/plugin_api.inc.php:external_plugin');` probably gives a boolean, so debug in smarty.inc show method is aways set.

**Comment by garvinhicking** [comment]
Yes, the /* ... */ comment there is intentional, we want to have that. This is so that users can see from where the output comes.

If you meant something different, please reopen and describe in depth.

**Comment by ophian** [comment]
If that is intentional to have for all, I do not see a reason do that via debug option, as it could be placed to the tpl much more easily. :) I for my own think, I do not want the public to read my fullpath, if not really necessary.

**Comment by garvinhicking** [comment]
I have posted this on the forums, there's a thread about why I think this is needed and required: http://board.s9y.org/viewtopic.php?f=11&t=20286

"debug" might not have been the right term, I'm sorry for that.

We need to have a dynamic feature that always reveals from where a tpl comes from. It is too much work to do it in each TPL. Also, other users might not do that in their custom templates, and then they would not easily see where a file is fetched from due to the complex fallback chaining.

We can change the debug statement to only use the relative path starting from the serendipity path if you like, I wouldn't mind.

**Comment by ophian** [comment]
> We can change the debug statement to only use the relative path starting from the serendipity path if you like, I wouldn't mind.

This would be good I think. Then this is a valid surplus value to have for all.

**Comment by garvinhicking** [comment]
OK! Just committed this change.
