### ISSUE TITLE
Maintenance Section: Show unused plugin tables

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#332]
The maintenance section could show a list of tables (of core and plugins) that are currently not used. This is predecessor of #318 and already partly discussed in #317.

**Comment by onli** [comment]
> Designwise there could be some makeover. The boxes are really large with a lot of whitespace.

@yellowled The lists created by this feature are rather large, which leads to the equal height mechanism enlarging all the other small boxes, which looks bad. Shell we just disable the function, or do we have max-height mechanism?

**Comment by onli** [comment]
@garvinhicking In my tests, that feature seems to be working fine. I propose we clean it up a bit )I still would like to hide the legacy-array) and move it to master.

**Comment by yellowled** [comment]
Hmmm. We keep running into issues with the equal_heights funtionality. I still think it is a good idea to some extent, but it might not be wise to always make *all* boxes equally high. I think it mainly looks bad because all boxes in a group get the height of the largest box. It would not look bad if the equal heights only applied to a row of boxes (i.e. all boxes in a row get the height of the largest box in the row).

That is, coincidentally the way `flexbox` does equal heights, so we could just use that. [Browser support for flexbox](http://caniuse.com/#feat=flexbox) is not great (IE >= 10 only), but we can do a fallback.

Of course, we can just disable it for the time being, but I don't think that looks much better.

> do we have max-height mechanism?

A what?

**Comment by onli** [comment]
> do we have max-height mechanism?

max-height. The equal height would not look half as bad if rows that do not need to be enlarged don't get too big, if they have a maximum. Flexbox should take care of that though. I'm ok with using that instead.

**Comment by yellowled** [comment]
> The equal height would not look half as bad if rows that do not need to be enlarged don't get too big, if they have a maximum.

There is no good way to do that with the current equal heights solution because that applies the `min-height` for the equal heights as an inline style which is hard to override.

I'm okay with giving flexbox a go here, but it's going to take some time to implement and test. I'll take a look if we have related issues and create a new issue for that.
