### ISSUE TITLE
Problem with Umlauts

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#338]
Please have a look: http://www.deimeke.net/dirk/blog/index.php?/plugin/tag/fundst%C3%BCcke

(The tag is called "fundstücke").

Serendipity 2.1-alpha1 und PHP 5.4.16

**Comment by bauigel** [comment]
How did you generate this links? i use tags with umlauts too and for me
they look like this:

Text: "thügida"
Link: https://bernd.distler.ws/plugin/tag/th%C3%BCgida

Serendipity 2.0.2-alpha1 and PHP 5.6.6

>

**Comment by ddeimeke** [comment]
Just go to my blog and select the tag beneath one of the "fundstücke" articles.

**Comment by ophian** [comment]
@ddeimeke 

But this works
http://www.deimeke.net/dirk/blog/index.php?/plugin/tag/fundst%C3%83%C2%BCcke
`http://www.deimeke.net/dirk/blog/index.php?/plugin/tag/fundst%C3%83%C2%BCcke`, which is ü = `Ã¼`.

While thinking about this, I found another small bug which could (_see below_) relate to your issue. Doing this, I re-discovered some changes and fixes I already coded this autumn, but then somehow forgot to commit to the public.

I said "_could_", since it is an en/de-coding UTF8 issue what you have. This may have to do with some bad encode/decode conversions, maybe missing the PHP mb_* functions, or is a matter of a "_false_" DB table collation or setting.
Before I commit this or give you the chance to check this up before, you may please check what your freetag plugin option: `(MySQL) Database collation for the entrytags.tag column (auto-detected)` says and if that really corresponds to your database {PREFIX}_entrytags table collation. I think that might be the real culprit in your case.

**Comment by ddeimeke** [comment]
I think, you are right. Table is collated with "latin1_swedish_ci" which was correctly autodetected by the plugin.

But the blog itself is configured to use UTF8.

php-mbstring is installed.

**Comment by ophian** [comment]
Hmmm, then
`SHOW FULL COLUMNS FROM `serendipity_entrytags` LIKE 'tag'`
should give 
`Field 	Type 	Collation 	Null 	Key 	Default 	Extra 	Privileges 	Comment `
`tag 	varchar(50) 	latin1_swedish_ci 	NO 	PRI 	NULL		select,insert,update,references `
which should be OK, I assume, since I have the same (with blog using UTF8) and my Umlaut tags are working.

Please add a temporary `echo '<pre>'.print_r($eventData).'</pre>';`
to 
https://github.com/s9y/additional_plugins/blob/master/serendipity_event_freetag/serendipity_event_freetag.php#L1250
and open
http://www.deimeke.net/dirk/blog/index.php?/plugin/tag/fundst%C3%BCcke
At page bottom you should see
```php
Array
(
    [orderby] => timestamp DESC
    [and] => WHERE isdraft = 'false' AND e.timestamp <= 1449666900 AND entrytags.tag = _utf8  'fundstücke' COLLATE utf8_general_ci 
    [group] => GROUP BY e.id
    [distinct] => 
    [joins] => INNER JOIN serendipity_entrytags AS entrytags ON (e.id = entrytags.entryid) 
)
```
I assume the [and] ... AND entrytags.tag = row result looks different in your case and either is not using utf8, or has no tag to search for. Please paste.

**Comment by ddeimeke** [comment]
Show full columns generates the same output.

Please check
```php
Array 
( 
    [orderby] => orderkey DESC, timestamp DESC 
    [and] => WHERE isdraft = 'false' AND e.timestamp <= 1449668700 AND (ep_access.property IS NULL OR ep_access.value = 'member' OR ep_access.value = 'public' OR (ep_access.value = 'private' AND e.authorid = 1)) AND entrytags.tag = _utf8 'fundstücke' COLLATE utf8_general_ci 
    [group] => GROUP BY e.id 
    [distinct] => 
    [addkey] => ep_sticky.value AS orderkey, 
    [joins] => LEFT OUTER JOIN serendipity_entryproperties ep_access ON (e.id = ep_access.entryid AND ep_access.property = 'ep_access') LEFT JOIN serendipity_entryproperties ep_sticky ON (e.id = ep_sticky.entryid AND ep_sticky.property = 'ep_is_sticky')INNER JOIN serendipity_entrytags AS entrytags ON (e.id = entrytags.entryid) 
) 
```

Please check for yourself.

**Comment by ophian** [comment]
Good we checked this...
I now would declare the freetag entrytags table and the conditions for en/de-codings to not be the issue of your issue, I think?!

The first thing to do, is to move the entryproperties plugin down under to the last place in your plugin list **always**. This should be done automated normally, but sometimes this does not happen (I've seen this happen before too). Is that the case and does this already change something?

I would now assume, it probably is this `ep_sticky.property = 'ep_is_sticky'` in the query and we would need to set a `$addData['noSticky'] = true` or set `$serendipity['skipSticky'] = true;` in the freetag plugin to not let this happen... , but I need to know what is your special case in difference.

I need to think about this a while.

In the meanwhile you could tell us which entries sticky property is set and which options in entryproperties are set in your personal case, to get an idea of what happens....

**Comment by ddeimeke** [comment]
Entryproperties now is the last plugin.

To be honest, I can not remember, why I am using the plugin. I can imagine it is because of the possibility to deactivate formatting plugins in specific articles.

**Comment by ophian** [comment]
> To be honest, I can not remember, why I am using the plugin. I can imagine it is because of the possibility to deactivate formatting plugins in specific articles.

AND much more! For me it definitely is a must have plugin with lots of magic! :)

What about the other questions?
I can see "just moving" is not helping, but as for the sql query data, does it still check for sticky?

It would be interesting to get (1) the whole SQL query string (remove all the added ep things) and throw that into phpmyadmin to see if that gives a result... 

[1] you could do that by uncomment this line once: https://github.com/s9y/Serendipity/blob/master/include/functions_entries.inc.php#L439

**Comment by onli** [comment]
Does this seem like a bug in the current version, or more like a leftover from old times when mysql created the database with local charsets? Is that something we can fix?

**Comment by onli** [comment]
Seems to be fixed.
