### ISSUE TITLE
PMA 4.x versions do not allow to edit per row in non unique key tables

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#341]
Discussion in http://board.s9y.org/viewtopic.php?f=10&t=20353&p=10442825#p10442825

I suppose and am afraid we will not change the developers mind keeping edit by row with non unique key tables, like S9y uses quite often, for example in `serendipity_config` or `serendipity_options`. Since even Debian Jessie PMA package is a 4.4.2.x version, I assume this will hit us more and more in the next future. We should rethink our use of these kind of db tables. (_Are we able to do this "easily"?_) Advanced Users will always find a way on how to get around this restriction, but this is nothing we can hope to be usable for the masses, I think.

I don't think ignoring the 4.x branch of PhpMyAdmin is a solid way into future, since this is the absolutely most used database administration tool in web based hostings.

Garvin?

**Comment by garvinhicking** [comment]
This is one of the most ridiculous changs of PMA. It makes no sense to me to remove such a feature. However I haven't read up on the reasoning of those changes (I guess this can be re-enabled with a config setting in PMA).

Our DB schema for this is solid, no unique key is needed. This thing will hit PMA hard, not us. It's simply stupid.

(Thanks for bringing this up, I'm simply upset by the PMA handling of this, not at you)

**Comment by onli** [comment]
@garvinhicking I wouldn't want to change existing databases for this, but wouldn't it be an improvement to make `name` a Primary Key in serendipity_config? Should be unique always anyway, or?

**Comment by garvinhicking** [comment]
We'd need a combined primary index on (name,authorid) because the same name can be set for multiple author ids. I believe the reason we didn't do that is because SQLite and PGsql behave differently there, and no unique SQL can be used for such a combined primary index or something like that...

**Comment by yellowled** [comment]
This was a single issue with PMA after setting a configuration to an inappropriate value while trying to switch to https, if I got all that right. It's not like end users need to use PMA on a weekly basis, and if they need to access the DB at all, we can always endorse adminer, which should be easy enough to set up and use for everyone.

Then again, most shared web hosters *will* pre-install PMA. I'm not sure they allow to tweak it's config, though.

**Comment by ophian** [comment]
I did not find anything either, except somewhere around 4.0.0 release version there was a data loss by such a command, which made them (silently) close this door, I think. Else it was only possible to work on these kind of table rows with a pumpgun shot eg `UPDATE `table` SET a = 'bar' WHERE a = 'text' AND b = 'text' AND `c` = 'text' LIMIT 1 ;` In most cases this will work, but in some it does not. This is why it is valid to be strict ... but they should have allowed a fallback, though.
I assume there is no config option to revert to a pre-4.0 behavior by now. 
I counted at least 15 non unique s9y tables, which can't get accessed any more with PMA 4.x  in a normal s9y installation. We would never need to do that with all of them, but some three are really bad to handle now. At least working in _config and _options and _plugins was a need from time to time!

**Comment by garvinhicking** [comment]
Small sidestep (as you all seem to know, I'll just mention this for the completion's sake of my argument/case)

To edit rows with PMA  they (actually "we", when I was an active member of the PMA team) simply appended a unique WHERE statement when editing single rows of a table that had no unique or primary key.

One problem of the solution was that such unique WHERE conditions could easily have a lot of characters (especially when blob/large text data was involved), so HTTP GET reuqests no longer worked. PMA then switched editing rows to issue HTTP POST requests.

What Ian mentioned was the next caveat, it could happen that multiple rows got updated which might not produce the expected behaviour. A "LIMIT 1" was added, which could however also create unwanted results.

Now the proper way for PMA to fix this would actually really be easy: Revert to the old behavior, and simply issue a SELECT ... WHERE (condition) statmeent when editing a row and check if this would affect a single or multiple rows. Then a warning message could be displayed or some other UI mechanism to make the user aware of what can happen. 

Simply removing the ability to edit such rows will definitely create a backlash for the PMA functionality. Maybe if I find the time I'll create a bug report on their tracker to ask why this isn't the case, maybe I'm missing a point.

However I really don't think this should be a reason for us to change a working DB schema, especially if this means we'll have to overcomplicate DB table creation for SQLite/PGSQL and other layers for tables that don't really need unique keys...

**Comment by ophian** [comment]
> Maybe if I find the time I'll create a bug report on their tracker to ask why this isn't the case, maybe I'm missing a point.

Oh yes, please! :+1: 
(And I always thought our table scheme was rock solid!)

**Comment by onli** [comment]
> I believe the reason we didn't do that is because SQLite and PGsql behave differently there, and no unique SQL can be used for such a combined primary index or something like that...

If it was only postgres and sqlite differing, we should be able to handle this. The syntax for postgres seems to be  `CONSTRAINT code_title PRIMARY KEY(column1,column2)`, sqlite uses `PRIMARY KEY (column1, column2)`, as well as mysql.

I'd like that. Not primary for PMA, but because it would be good to force the uniqueness in the database, and it should win us a few performance pennies. Is it ok if I re-open and try to find a patch for at least some of those tables? Maybe @ophian could provide a list.

**Comment by garvinhicking** [comment]
Sure! If we can have a way to enforce proper uniqueness across all db layers I wouldn't mind; it would be clearer at least for the config db table. We'd need to check on others case by case to see how or if uniqueness should be applied.

**Comment by onli** [comment]
We don't need any code changes. I erred above, according to the documentation postgres has exactly the same syntax for primary keys as sqlite and mysql. In fact, we were already using that syntax in some places, so all we have to do is to do add primary keys to the tables that were missing them.

The one thing to look out for are bugs caused by this, because maybe Garvin's memory of issues with that has a basis (maximum primary key length in mysql for example).

**Comment by onli** [comment]
No other tables to add primary key to? @garvinhicking, @ophian?

**Comment by ophian** [comment]
> Maybe if I find the time I'll create a bug report ...

@garvinhicking Have you already intervened?

**Comment by ophian** [comment]
If you manually ALTER existing tables, wouild that need to be
```sql
ALTER TABLE `serendipity_config` ADD UNIQUE (`name`, `authorid`)
```
or
```sql
ALTER TABLE `serendipity_config` ADD UNIQUE `unique_index`(`name`, `authorid`);
```
...or even
```sql
ALTER TABLE table_name ADD CONSTRAINT constraint_name UNIQUE (column_name)
```
???

**Comment by garvinhicking** [comment]
I just did, thanks for reminding me: https://sourceforge.net/p/phpmyadmin/bugs/4963/

As for the SQL, I think the third one is the most "incompatible" one. The first two should both work, I'm not sure if any is preferrable.

**Comment by garvinhicking** [comment]
Update: They implemented a config option to restore the behaviour! :-)

**Comment by ophian** [comment]
Which is sort of useless for the users we are talking about (ISP usage), since they can't extend the config themself, I assume. :(

**Comment by garvinhicking** [comment]
I am not that proficient with recent PMA versions but I thought that certain config variables can be influenced by the user...?!

**Comment by ophian** [comment]
I don't know and am not sure about this. Imagine a common Debian ISP istallation. The config is in /etc, isn't it? They would at least need the rights to access the setup script, I think.
Probably these users will even have to wait for several years until they could use this or that anyway.
Because of this I think we should fix the missing uniqueness for upgraders too, not only on new installs.
Or at least push a information NOTE about this (and how to get around it) to the NEWS file or something.

**Comment by onli** [comment]
I'll close here, this was not an issue later on.

**Comment by ophian** [comment]
Which does not mean that this is solved, btw.
There are a lot of tables left where we will not get access for years. We should take care ourselves, not waiting for a future PMA change, which might never be noticed by users...
