### ISSUE TITLE
can we securely check mod_rewrite before allowing to use as config option?

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#342]
Regarding this thread (http://board.s9y.org/viewtopic.php?f=2&t=20395) and some others we had in the past, wouldn't it be worth to either write
```
<IfModule mod_rewrite.c>

  # Turn on
  RewriteEngine on

  # Conditions and Rules
  RewriteCond ...
  RewriteRule ...
  ...

</IfModule>
````
to both of the rewrite tpls
https://github.com/s9y/Serendipity/blob/master/include/tpl/htaccess_rewrite.tpl

or check this via `in_array('mod_rewrite', apache_get_modules());` for Apache modules or `strpos(shell_exec('/usr/local/apache/bin/apachectl -l'), 'mod_rewrite') !== false` for CGI usage or any other check for other non-Apache Servers, before we allow to set mod_rewrite per option?

I never use other than moduled apaches, so I can't really judge this. This all to avoid totally blocked Serendipity installations. Are we able to secure this option set to mod_rewrite a little more?

**Comment by onli** [comment]
> `<IfModule mod_rewrite.c>`

:+1:

**Comment by ophian** [comment]
I assume we cannot do this singulary per htaccess, since we request the config set mod_rewrite option in some other places too and trust its value working. The IfModule would just not force an immediate accessible error.

**Comment by garvinhicking** [comment]
What do you mean with "set mod_rewrite option in some other places too"?

IMO using this <IfModule> in .htaccess is something we could implement easily and I hope that it woulnd't break thinks. Committed to 2.1.x!

IMO using apache_get_modules can be problematic because in many cases the PHP implementation doesn't allow for it (Providers usually compile PHP via FastCGI nowadays, not Apache modules).

Using apachectl would be hard to find out in which location that file is, and shell_exec would be required, so I think this route will make more trouble than it solves.

Thus, I think adding ifModule should really ease up things to prevent fatal errors for the whole site. Good thing you brought this forward, thanks!

**Comment by ophian** [comment]
> What do you mean with "set mod_rewrite option in some other places too"?

Well, writing this, I had in mind, that we had some occurences in Plugins for example, which just check if mod_rewrite was set true to build URLs etc. This would now be true, but would not actually work in these rare cases, where servers do not have it set active. Thats what I meant to say. Isn't that the case?
I think we would need an additional check and throw an exception or notice to the user in case it is not active.

**Comment by ophian** [comment]
How about this little trick? http://christian.roy.name/blog/detecting-modrewrite-using-php
see also http://christian.roy.name/blog/detecting-modrewrite-using-php#comment-170

**Comment by garvinhicking** [comment]
Plugins actually only check for the 'rewrite' option, not for MOD_rewrite specifically. If "rewrite" is enabled, it can either be apache errorhandling und mod_rewrite (or manual nginx rewriting).

If a user enables rewriting without it working, he'll recognize it that all links will not work.

The ifmodule check is there to prevent fatal errors so that the site is not available, which is our primary goal here IMO. The user will then need to disable URL rewriting if he notices it won't work on his/her server.

The URL tip is a nice one, but this means the .htaccess already needs to be created with the setEnv directive. That's a chicken/egg problem, I don't think we can implement it. If anyone wants to have a try at this, feel free to do so, but for me it's not important enough to make more work in this area, because it also makes the code much more complicated (it already is complicated when s9y performs a HTTP request to test if its implemented .htaccess file creates trouble in the installer)....

**Comment by ophian** [comment]
OK fine, thanks for committing.
