### ISSUE TITLE
check, update or remove default/admin/serendipity_editor.js file

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#363]
If it is a copy of an old compiled version, please update or check if we still need to keep this for any case.

If remove, do not forget to update the 2.0.2 remove task https://github.com/s9y/Serendipity/blob/master/include/functions_upgrader.inc.php#L192

Thanks.

**Comment by onli** [comment]
I'm not in a position anymore to reason about the fallback chain - that got rewritten without me being involved, and serendipity_getTemplateFile got complicated.

I think it is still possible for a template to circumvent 2k11, and to not get the serendipity_editor.js.tpl file then, falling back to serendipity_editor.js. But why not copy the tpl to default? Probably because I'd have loved to remove default completely.

**Comment by yellowled** [comment]
Erm, why is this even open/an issue? As far as I understand, it is a “directive” – it can never be “completed”, right?

**Comment by onli** [comment]
Maybe. But I think we can solve this by copying the serendipity_editor.js.tpl to default and remove the serendipity_editor.js. from there, then we can close here. On the other hand, there is no alternative admin backend with which we could test this, so maybe just close here and see whether it becomes a real issue?

**Comment by yellowled** [comment]
*Can* it even become an issue unless someone decides to use `default` as the admin backend in s9y >= 2.0? Because I assume that the chances of that ever happening are slim to none …

**Comment by onli** [comment]
I think it could happen when using a new admin theme and setting its engine to default. Like I said, I don't get anymore whether that still is possible. I'll close here, let's wait for a real bug before worrying about that file.
