### ISSUE TITLE
revisit language constants

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#368]
I searched for "is:issue is:closed lang in:title", but we had not have an issue like this yes, since I'd like a thread to cover them all found by time.

To start with, I found:
- [ ] BASE_DIRECTORY and PARENT_DIRECTORY constant both meaning the same approach. Shouldn't we skip the latter PARENT and use BASE only?

**Comment by garvinhicking** [comment]
I believe this is a translation issue.

BASE_DIRECTORY in english means "originating directory" and could be used for that, and PARENT_DIRECTORY would mean "directory that serves as a parent for another hierarchy".

To translate both with "Stammverzeichnis" in german might boil down to the same, but in reality BASE_DIRECTORY should be "Quellverzeichnis" and PARENT_DIRECTORY should be "Stammverzeichnis".

But if we renamed those, we might make trouble where this disctinction in german was not foreseen.

Since either of these Constants can be used in plugins or templates, we cannot simply remove either of them, so we should live with that dupe.
