### ISSUE TITLE
[serendipity_event_bayes] Recovered comments from Bayes trashbin are deleted

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#374]
Now it happened the second time.

I tried to recover some comments from the Bayes trashbin, but they were deleted.

My blog runs with "Serendipity 2.1-alpha2 and PHP 5.6.16".

Any ideas?

**Comment by onli** [comment]
They all were deleted instead of being restored? Which database are you using?

**Comment by ddeimeke** [comment]
Yes, all. I am using MariaDB.

I picked two comments to be restored and all five comments were deleted.

**Comment by onli** [comment]
You probably just mistyped that, but you meant all two, right?

I will have to try to reproduce the bug.

**Comment by ddeimeke** [comment]
No, I ment all five.

Commenters always try to resend their comments, if it didn't work the first time.

So I had two identical comments from one person and three identical comments from another person.

I only want to restore one comment each.

**Comment by onli** [comment]
I just pushed a new version, 0.4.20, to additional_plugins (https://github.com/s9y/additional_plugins/commit/b8757a5879c97b66bd27b22afc95380c2c78997b), with which it works for me again.

It is a typical "I don't know why that ever worked" bug. setupDB deleted the recycler because of a stupid and wrongly written if statement (by myself, of course). That probably did not surface before because the code stopped one line before deleting the content of the recycler, when trying to create the recycler despite the table already existing. And something changed which makes the code continue now.

It is the best explanation i have, but it is a bit unlikely that it is the right explanation. It might still be another bug, so I will leave this open. After you had the chance to test that, please report whether it worked.

**Comment by ddeimeke** [comment]
Installed.

Waiting for spam comments to come in. :-)

**Comment by onli** [comment]
I had a small mistake in it and pushed now a patch, version 0.4.21. Should not concern you at all (only sqlite-users), just so you are aware.

**Comment by ddeimeke** [comment]
Thanks Malte! I am aware and did not install .21 ...

**Comment by onli** [comment]
You could install it, it should change nothing.

**Comment by onli** [comment]
Dirk, did you have the chance to test this?

**Comment by ddeimeke** [comment]
Oh, yes, sure.

I once recovered a comment and nothing was deleted.

So in my opinion everything is working fine.
