### ISSUE TITLE
Dedicated pages by plugins not working

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#375]
Current master - "cleanup of index" commit bug, breaking static pages routing and accessment. (Prev index worked well!)

Every plugin using a "static" page, eg. `http://www.example.org/pages/usergallery.html` is not working any more.

**Comment by ophian** [comment]
> Current master - "cleanup of index" commit bug, breaking static pages routing and accessment. (Prev index worked well!)

Since this is an essential part for Serendipity, and nothing happened for 5 days, and there are even some more questions regarding your index.php file change, I would like to have this commit removed quickly - at least until you found time to check this and other issues more deeply. There are people already using 2.1-dev for development and even in public cases.

**Comment by onli** [comment]
Ian, this is a dev version. I saw the report and will look into it. If people are using an unstable version, things are bound to be unstable, this does not warrant a revert.

**Comment by onli** [comment]
Hi Ian
Now I have a bit of time, and since it seems urgent to you, thought I look at this first. Install the freetag-plugin, open the tag page – and that works.

The usergallery-plugin indeed does nothing on that link, but I don't know it, that could be something else. Which other plugins with dedicated plugin-pages do not work?

**Comment by onli** [comment]
Okay. The problem was that the $uri-variable that gets passed to the genpage event in include/genpage.php as $eventData – on which some of those plugins base their decision whether their page is selected – was set in index.php. But with the rewrite we no longer include genpage.inc.php in index.php, but in one of the serve route functions. $uri in genpage and $eventData in the plugins thus was empty.

I workaround set by setting the variable in genpage.inc.php as well. It is possible that this does not catch all modification made to the variable normally, but ideally there should be none. In my short test it seemed to work.

**Comment by ophian** [comment]
Fine. Will check this again later.

You also removed the `if (!defined('NO_EXIT')) {` around exit. At least freetag relies on this. Did you check all those plugins which `@define('NO_EXIT', true);` to properly work as designed?

**Comment by onli** [comment]
Not at least, only the freetag-plugin used that. See the comment on https://github.com/s9y/Serendipity/commit/4bb10f5b70fa60b1542c5ea99444761f8a86d6b0#diff-828e0013b8f3bc1bb22b4f57172b019d . I'm not quite sure whether I fixed that in the plugin or whether that is still something to do.
