### ISSUE TITLE
addToCSS function breaks order of generated CSS

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#384]
The dynamically generated stylesheet `serendipity.css` is supposed to contain styles in a very specific order to ensure a proper CSS cascade and to make it as easy as possible to still override styles.

This order is

1. plugin styles (as emitted by event and sidebar plugins via hooks(?))
2. fallback styles (`templates/default/style_fallback.css`)
3. theme styles (`style.css`)
4. user styles (`user.css`)

However, a few plugins use a function called `addToCSS`, which *only* emits plugin styles if styles for those CSS selectors (ids, classes) are *not* defined in the theme styles. While that is actually a pretty smart solution, these styles are **not** emitted at 1., but between 3. and 4.

I think that should be fixed, if only for consistency (it is technically not necessary because overriding these styles – which is our main reason for the specific order listed above –  is in fact even easier).

These plugins are

* serendipity_event_freetag
* serendipity_plugin_flickr
* serendipity_plugin_twitter

Again, I do *not* propose to remove or replace `addToCSS`, it seems like a pretty smart solution. If possible, plugin authors should probably use it more often.

**Comment by onli** [comment]
If not replacing `addToCSS`, which solution do you propose? I'd move the css to the css event to fix the order, but you do seem to have something else in mind?

**Comment by yellowled** [comment]
No, I just can not really propose a solution because I don't know how this works (technically). The CSS emitted via `addToCSS` should be emitted along with the other plugin styles (1.), but it should still maintain the functionality to not emit CSS at all if said styles are defined in the theme styles.

If “move the css to the css event” does just that, perfect.

**Comment by garvinhicking** [comment]
Actually the order is:

1. style_fallback
2. style.css
3. event plugins
4. user.css

In step 3, plugins should append their output to $eventData. If they do NOT do this however and use echo, then their CSS is sorted at first place.

So we could update each and every plugin to not echo the CSS, but pass it to eventData. The plugins which do this properly are the ones you listed, we would need to fix all plugins that didn't. Since this is much work for en effort without positive effect, we decided to close this and ignore. :)
