### ISSUE TITLE
Dashboard ignores group rights

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#385]
Comments, entries and drafts of other users are viewable also when they are not editable. See http://board.s9y.org/viewtopic.php?f=10&t=20639&p=10444507

**Comment by onli** [comment]
Even if https://github.com/s9y/Serendipity/commit/97c43af83e9606baabf009c059c3ec660cbf782b would correct the comment issue (it does not) there is still the problem of the drafts, entries and buttons that does nothing.

**Comment by ophian** [comment]
There is a remaining question left (in that mentioned thread) that we have to clear about this and other places:
Shall S9y stick with serendipity_checkPermission() levels and/or allow non-privileged "standard users" to edit their blog-entries belonging comments? Shall we disable edit buttons for them at all or allow access? And what about categories and at last, what about ML items? You remember we have set ML to authorid 0, which prevents a checks by authorID any further. But do we really want those non-privileged "standard users" to edit global items or categories?

I have ideas how to workaround this restriction (at least for the dashboard comment access) but that would "break" serendipity_checkPermission() levels at this point, since non-privileged "standard users" are not allowed to edit comments for example, by `serendipity_checkPermission('adminComments')`.

**Comment by yellowled** [comment]
Let's please discuss that *in that thread*.

**Comment by garvinhicking** [comment]
I've commented in that (german) thread on how I think it should be, if I didn't understand properly, please relay the actual problem to me so that I can understand. :-)

**Comment by ophian** [comment]
Shall we discuss setting categories privileges for "Standard Users" too in the forum?

**Comment by yellowled** [comment]
Does anyone still get what this is about? Is it fixed? Is the issue just stale?

**Comment by onli** [comment]
The original issue was about the dashboard showing controls to users in groups without the rights to do the linked actions. But it'S stale and tje majority of this is fixed, afaik. I'll close.
