### ISSUE TITLE
Entryproperties plugin: Add "update lastModified" checkbox

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#401]
Add a checkbox to the entryproperties plugin to allow updating lastModified (to be able to push entries to the RSS feed after modification).

**Comment by onli** [comment]
I think something got lost here. Turns out that s9y does already update the last_modified field in serendipity_entries when editing an entry (well, kind of expected). I'm not sure how the entryproperties plugin should come into play here here. When checking the checkbox, what should it modify to push entries to the top of the RSS feed?

We could change the **rss.php** to consider last_modified when fetching entries?

I think the ideal behaviour would be to have a checkbox (or just react when a lot changed) that marks the entry, and for marked entries `last_modified` is used instead of `timestamp` when determining the entry order for the RSS feed. And that flag could come from the entryproperties plugin. But that seems rather complicated to me, the SQL or the code needed.

Maybe we just give up on this feature and close this issue?

**Comment by onli** [comment]
Based on the small interest in this I'll close here for now.
