### ISSUE TITLE
[serendipity_plugin_piwik] Top10-List links wrong URLs

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#403]
The sites shown in the sidebar don't link back to the correct pages.

Have a look: https://www.deimeke.net/dirk/blog/

**Comment by ophian** [comment]
Maybe you should append the output of debug option true into file templates_c/piwik_debug.log after a while, to get an idea off why $piwik_array_pagesurls and $piwik_array_pagestitles seem to not correspond.

**Comment by ddeimeke** [comment]
```
2016-04-26 07:46:57 Actions.getPageUrls - API-URL: https://www.deimeke.net/piwik/index.php?module=API&method=Actions.getPageUrls&idSite=1&period=range&date=previous30&format=PHP&filter_limit=10&flat=1&disableLink=1&showColumns=label,url,nb_visits&token_auth=${TOKEN}

2016-04-26 07:46:57 Actions.getPageTitles - API-URL: https://www.deimeke.net/piwik/index.php?module=API&method=Actions.getPageTitles&idSite=1&period=range&date=previous30&format=PHP&filter_limit=10&flat=1&disableLink=1&showColumns=label&token_auth=${TOKEN}
```

**Comment by ophian** [comment]
Hmm, I dont think that helps, even when the token looks a bit strange to me...

Did you already read the readme? It says:

> known bugs
>
> In some cases (i think, it only happens if main/index-page is in the top xx-list) page-url and page-title of section "most read entries" are not for the same page. I don't know why, but Piwik gives different output for the fetching of url and title and at the moment i don't know how i could solve this problem.

I could imagine that you don't even need to merge $piwik_array_pagesurls and $piwik_array_pagestitles, since origin pagesurls `2016-04-26 07:46:57 Actions.getPageUrls - API-URL: https://www.deimeke.net/piwik/index.php?module=API&method=Actions.getPageUrls&idSite=1&period=range&date=previous30&format=PHP&filter_limit=10&flat=1&disableLink=1&showColumns=label,url,nb_visits&token_auth=${TOKEN}` should already have (or get) the label, shouldn't it?

Dirk, you need to ping Bernd Distler about this. He has no proper username for a mention here.

**Comment by bauigel** [comment]
​Best solution probably would be ​to take static url given by piwik and get
static page url from s9y-database. We talked about this at s9ycamp.
Currently if have no time to work at this. Maybe end of may, if noone else
will find a good solution.

**Comment by ddeimeke** [comment]
@ophian Yes, I know. Bernd - @bauigel - asked my to open an issue for this.

**Comment by onli** [comment]
This died because the API did not support to do it properly (mainly quoting @bauigel here) and usage of Piwik did fall out of favour. I'll close this, but no one would block an implementation of course.
