### ISSUE TITLE
Feature request: Send error messages to the blog owner

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#412]
It would be a good idea to have error messages sent to the blog owner.

No user should ever see one (if possible), the user should only get a notification that an error occured which was reported back to the admin.

Blog owners depend on users to report errors back which is not a good idea in my opinion.

("Standard Error" to Mail, "Standard Out" to Browser).

**Comment by garvinhicking** [comment]
The ideal way IMO would be to ensure that on production blogs, errors are not displayed, but instead logged to the PHP error_log, which an admin/owner should check from time to time.

IMO sending mails with error messages is something that could spam your inbox or would be really annoying

**Comment by ddeimeke** [comment]
Agreed, in my opinion it should be configurable. Like it is for the antispam-plugin.

Destination: Logfile, Database, E-Mail, none

I don't mind getting a lot of mails, they are filtered anyway.

**Comment by garvinhicking** [comment]
Ideally inside our include/compat.inc.php file we would like to patch the function:

errorToExceptionHandler

and make that check for the to be created configuration option "Send errors to..." (i.e. $serendipity['errorReportingMethod'], and then perform the action to log to database or to file or email. The hardest thing might be that at this point we don't have the ability to call serendipity_sendmail() or perform database operations or even access $serendipity array for the config option, so that would need testing, and only be performed if it is available.

**Comment by th-h** [comment]
I'm not sure that I'd would be a good idea to implement application level error logging in s9y, especially considering our quite small developer base. AFAIS it's mostly standard for PHP applications to log errors to the error_log (only).

I'd vote to close this issue. @garvinhicking @onli @yellowled

**Comment by yellowled** [comment]
That's basically what @garvinhicking said in https://github.com/s9y/Serendipity/issues/412#issuecomment-227974586. (I don't really have an opinion here.)

**Comment by th-h** [comment]
Closing this issue for now as it got no traction for three years.

s9y can use the PHP error reporting facilities that allow to log to files or syslog; this allows for a very granular further processing, especially since PHP applications nowadays usually no longer run as a web server module, but via FPM or similar. which allows even more individualized logging configurations.
