### ISSUE TITLE
Smileys lost ...

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#416]
The internal editor and the comment window do not show smileys anymore.

**Comment by garvinhicking** [comment]
I guess this will also be related to the serendipity_getTemplateFile() 
change @onli ?

**Comment by onli** [comment]
Yes. The plugin does not bring its own smiley graphics, it relies on the default template to provide them. 2k11 does not bring them, and the the changes to serendipity_getTemplateFile() stop templates/default/ being a last fallback.

We can either re-add templates/default/ as a generic fallback, move the graphics to 2k11 or move them into the template. Imho, with the simplification it is clear now that themes override plugin, and thus the plugins should bring its own default. I'll look how complicated that might be.

**Comment by garvinhicking** [comment]
Hm that sounds problematic to me also for other plugins that use 
gettemplatefile i.e. for the XML.gif graphic or something else.

This plugin is a good example, and it shouldn't come with its own 
emoticons, but rather use the ones of a theme... so we would need to 
merge all files from default into 2k11, where 2k11 doesn't provide such 
a graphic?!

(I haven't looked at the changes and new code of yours yet)

**Comment by onli** [comment]
> This plugin is a good example, and it shouldn't come with its own emoticons, but rather use the ones of a theme... 

I think it should come with its own graphics and fall back to them, but give priority to theme files. Or why do you think that? In that case, we might just move the files over to 2k11.

Having the files as fallback in the plugin is not as easy as it should be. We can't use parseTemplate, for one because it is not a template and smarty will error, and second because of its basename restriction. The easiest solution might be to add another function to the API, but I'm still looking whether that can be avoided.

> that sounds problematic to me also for other plugins that use gettemplatefile i.e. for the XML.gif graphic or something else.

That specific graphic seems to work fine in the usual plugins (category, freetags), also the syndication plugin is still working as intended. But sure, other plugins might get hit by this. It is unfortunate, but is the consequence of a problem missed in the alpha…

**Comment by onli** [comment]
After that last exchange I never pushed my solution :/ It should work now.

The images are however of bad quality. We should exchange them, either with better images, or with emoji (the font solution), maybe after #394 is fixed.

**Comment by ddeimeke** [comment]
Smileys are back. Thank you!
