### ISSUE TITLE
Add update notification for plugins

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#423]
To enhance the unified update plugins button, we want a notification message in case there _are_ updates available. So we need the ability to
- [ ] query Spartacus for available plugin updates ([related comment](https://github.com/s9y/Serendipity/issues/94#issuecomment-71096286))
- [ ] display a message in the backend dashboard (“X plugin updates are available")
- [ ] display the number of available updates as an additional badge on the “Update plugins” button (like “Update plugins [5]”)

Related:
- [forum discussion](http://board.s9y.org/viewtopic.php?p=10444455)
- #94 was the old version of this issue

**Comment by onli** [comment]
I had a try, and failed. To make this work, we'd first need:

 - [ ] A function that returns all installed plugins, complete with version information
 - [ ] A function that returns all available plugins, again complete with version information

This really is a task that should not be hard, but really is hard, just because of how insane the plugin api is.

There are parts of this: One can call `backend_plugins_fetchlist` to make spartacus fetch a list of available plugins, but somehow I ran into a bug where I could not toggle between event and sidebar plugins (and that really should not work via a global variable) and there is no way to get both. For the installed plugins the api has some plugins, like `get_installed_plugins`, but nothing that returns them with all meta information.

@garvinhicking Am I missing a straightforward way to get the information needed? What do you think about extending the plugin api for this?

**Comment by onli** [comment]
Also, why doesn't this work?

```
$classes = serendipity_plugin_api::enum_plugins();
$currentVersions = [];
foreach ($classes as $class_data) {
    $pluginFile =  serendipity_plugin_api::probePlugin($class_data['name'], $class_data['classname'], $class_data['pluginPath']);
    $plugin     =& serendipity_plugin_api::getPluginInfo($pluginFile, $class_data, 'event');
    if (is_object($plugin)) {
        // Object is returned when a plugin could not be cached.
        $bag = new serendipity_property_bag;
        $plugin->introspect($bag);
        $version = $bag->get('version');
        $currentVersions[$class_data['classname']] = $version;
    }
    if (is_array($plugin)) {
        $currentVersions[$plugin['class_name']] = $plugin['upgrade_version'];
    }
}

$foreignPlugins = array();
serendipity_plugin_api::hook_event('backend_plugins_fetchlist', $foreignPlugins);
$foreignPlugins = $foreignPlugins['pluginstack'];

$pluginUpgrade = false;
foreach ($currentVersions as $plugin=>$version) {
    foreach ($foreignPlugins as $foreignPlugin) {
        if ($foreignPlugin['class_name'] == $plugin && version_compare($foreignPlugin['version'], $version, '>')) {
            $pluginUpgrade = true;
        }
    }
}
```
`pluginUpgrade` is never true - it is as if spartacus plugins already installed do not get returned by `serendipity_plugin_api::hook_event('backend_plugins_fetchlist', $foreignPlugins);`?

**Comment by th-h** [comment]
> it is as if spartacus plugins already installed do not get returned by `serendipity_plugin_api::hook_event('backend_plugins_fetchlist', $foreignPlugins)`

`serendipity_plugin_api::hook_event('backend_plugins_fetchlist', $foreignPlugins)` will only return plugins of one type, *event* or *sidebar*, depending on `$serendipity['GET']['type']`.

For plugin upgrades, we try to call that hook two times with different settings of `$serendipity['GET']['type']`, but AFAICS that doesn't work; you get either only *event* or only *sidebar* plugins. (When sprinkling `print_r` through the code you can see that the "merged" `$foreignPlugins` (after `array_merge()` on line 173) only has one type of plugins, never both.) Why the upgrader works for both anyway, I've got no idea.

I tried to duplicate the code for an upgrade counter, but that did only work for one type of plugins, never for both.

Work in progress at https://github.com/th-h/Serendipity/tree/thh-plugin-notifier.

**Comment by th-h** [comment]
> For plugin upgrades, we try to call that hook two times with different settings of `$serendipity['GET']['type']`, but AFAICS that doesn't work; you get either only *event* or only *sidebar* plugins.

I think I fixed that ... See #619.
