### ISSUE TITLE
Error messages if SQLite db is not writable

### ISSUE THREAD

**Issue by gnuheidix** [s9y/Serendipity#427]
I've noticed after some fiddling that no error messages are being sent to the users in case s9y fails to write to the SQLite db. Commenting, saving new blog posts, changing passwords,... everything responded with a success message although nothing has been changed at all.

**Comment by onli** [comment]
Thanks for the report. I can confirm the issue.

I'll write down what I found so far. There are multiple problems. One seems to be that the PDO driver acts as if everything is alright despite the file not being writeable. We would have to check that manually by testing against the number of changed rows, which seems to be accurately 0. I'm not sure that will work properly in the end. Alternative is to just fail on initializing the driver when the file is not writeable, but that would mean a non-writeable db takes down the blog. Maybe that is okay.

Even if properly checking whether an insert/update succeeded, the configuration will still always report success, the code is just not checking whether updating the changes in the database succeeded. That would need to be fixed.

**Comment by garvinhicking** [comment]
Idea: We make the admin dashboard page call the serendipity_db_probe() function and give an error/notice, if that fails. Then make the sqlite driver additionally check for write permissions and display that.

**Comment by gnuheidix** [comment]
This will only make the problem visible to somebody who accesses the admin dashboard, right? That's a good start.

I prefer to have s9y as resilient as possible. That would mean that all functions like displaying blog articles, search,... should still work flawlessly when writing to the database is not possible for some reason. The problem with this behaviour is, that issues with a read-only database can remain unnoticed a fairly long time.

I consider it most important that user input doesn't get lost somehow. e.g.: Users who commit comments to blog posts get success messages but their comments were not saved at all. They deserve a proper error message that the system can't accept the comment at the moment and that they have a chance to copy their comment from the rejected comment form in order to try it again later.

In order to notice problems in s9y when they occur, I would like to have a way to monitor the health of the s9y application. This mechanism could be used in the admin backend to display problems. Furthermore, an external monitoring tool like Munin could poll this information regularly an warn operations personnel.

**Comment by onli** [comment]
I now implemented the error message in the dashboard. It checks where the file is writeable and complains if not.

Untranslated, because I know that @stephanbrunker has something prepared for the lang files and I did not want to create a merge conflict for him. I hope we remember that later, though this error should not be visible often anyway.

@gnuheidix, what you describe is sound. It would be ideal if the blog just worked read-only and properly showed error messages when writing to an unwriteable database. That might be doable by adding a check to serendipity_db_query and serendipity_db_schema_import and manually returning an error code whenever an INSERT or UPDATE query is given while the database file is readonly. Maybe something you'd like to work on?

For now I'll close here though, please re-open if necessary.
