### ISSUE TITLE
PHP 7 errors in the new 2.1-RC1 release

### ISSUE THREAD

**Issue by halojoy** [s9y/Serendipity#441]
I run the PHP 7.1.1. With error_reporting E_ALL.
First error is about mcrypt, which is a function about to be cancelled. It happens when logging in to admin the serendipity.
The other two errors are also Errors. One is when going for to writing a new article ....

1. PHP Fatal error:  Uncaught ErrorException: Notice: Function mcrypt_get_iv_size() is deprecated in C:\Apache24\htdocs\serendipity\include\functions_config.inc.php:426

2. PHP Fatal error:  Uncaught ErrorException: Warning: Illegal string offset 'authorid' in C:\Apache24\htdocs\serendipity\templates_c\2k11\0e\7d\85\0e7d853e4cdd6c566d22ee94d7681d9df43cadfa_0.file.show_plugins.fnc.tpl.php:153

3. PHP Fatal error:  Uncaught ErrorException: Warning: Invalid argument supplied for foreach() in C:\Apache24\htdocs\serendipity\plugins\serendipity_event_entryproperties\serendipity_event_entryproperties.php:421

I am sure there are more errors. Time will tell where they are. And how many.

**Comment by garvinhicking** [comment]
Thanks for giving that feedback to us. How exactly did you set error_reporting to E_ALL? Serendipity should by default take care to set it without E_NOTICE and E_DEPRECATED, and in debug environments at least without E_NOTICE.

We bundle some libraries and some code is not really doing all the isset() checks on unset variables, so that's still some code cleanup we eventually need to do (even though using such strict checks on script langauges is something that can be up for discussion ;)).

The mcrypt_get_iv_size() warning actually is interesting and I hadn't noticed. We will need to investigate how to replace that block of code to do encrypting of the auto-login cookie.

**Comment by onli** [comment]
Frankly, the whole related code (including password-hashing) is very much in need of a rewrite (it's actually on my list of things to do after 2.1). https://paragonie.com/book/pecl-libsodium/read/09-recipes.md might be a good starting point, though I have not yet wrapped my head around the concept of "autologin via cookie".

For the PHP 7 compatibility issues, thing is that we tested against 7.0, not 7.1.

**Comment by garvinhicking** [comment]
For our release candidates and beta, we always increase the error reporting to catch possible errors. The mcrypt and other message was a warning, that a "proper" release should not stumble upon. We will address an mcrypt replacement for the future serendipity version.

Having said that, we could not reproduce the second and third of your posted error messages, and believe they should not happen at this point with PHP 7.1. We are about to release the 2.1.0 version, so we would be happy if you can try that out and see if you can still reproduce your issues. If so, please feel free to reopen this issue!

(If you want you can set $serendipity['production'] = false; in your serendipity_config_local.inc.php to force Serendipity showing warning messages that would otherwise be surpressed in RCs/Betas/Alphas).
