### ISSUE TITLE
HTTP500: comment preview and submit crash on array

### ISSUE THREAD

**Issue by gnuheidix** [s9y/Serendipity#445]
The POST request which adds a comment can crash s9y in case the comment field gets modified into an array.
Request example: POST /index.php?url=archives/63-blablabla.html

Form-Parameter example 1: - see _serendipity[comment][]_ - preview used
![form_params](https://cloud.githubusercontent.com/assets/234757/22659968/f26f06dc-ec9f-11e6-85a5-99164dc24b33.png)
Form-Parameter example 2: - see _serendipity[comment][]_ - submit used
![form_params2](https://cloud.githubusercontent.com/assets/234757/22660477/f89a2f1c-eca1-11e6-8dd7-5144716d4f63.png)

Version: 2.1-rc1
Errorlog for example 1:
`PHP Fatal error:  Uncaught ErrorException: Warning: htmlspecialchars() expects parameter 1 to be string, array given in /srv/gnuheidix.de/include/compat.inc.php:516`

Errorlog for example 2:
`PHP Fatal error:  Uncaught ErrorException: Warning: trim() expects parameter 1 to be string, array given in /srv/gnuheidix.de/include/functions_routing.inc.php:342`

**Comment by onli** [comment]
I also saw #444.

In both cases my questions is: Can this happen in the normal UI? I think I miss the problem with those two crashes. Of course, we should handle all situations/all variations of input variables that might arise in normal use, and if normal use can cause this, then we need to catch it. But when PHP crashes because some input variable got modified, to my understanding that is not a problem at all, and also not something that can be prevented with reasonable effort.

Can you elaborate a bit why those two crashes are problematic? And @garvinhicking, please shut me up if I'm  spreading nonsense, not exactly sure I'm not missing something here.

**Comment by gnuheidix** [comment]
A well built web application should never respond with a 500 if somebody fiddles with user input. This should be handled by the input validation.
A 500 is only ok in case the server is low or out of on resources or a required external system like a database or so is unavailable.

Furthermore, in PHP web applications Fatals tend to produce stacktraces visible to users. That leaks security relevant system information depending on the level of (mis)configuration in php.ini.

**Comment by onli** [comment]
We actually try to control the amount of error output. In production mode, no stacktrace should be visible, if the user does not explicitly deactivate our configuration.

500 means internal server error. Those do happen if arguments are manipulated outside the bounds of the UI, and I think you'd find examples for this throughout the whole core. In this specific case, if you give an array to a function that expects a string, a 500 is exactly what is supposed to happen. But granted, PHPs auto-conversion makes that not a too convincing argument, since the input is also a string. Still, I fear that if we start to go down that route, we'll add input validation till 2030 ;) And PHP is not a language that would make it easy. Meanwhile we have some really user-facing bugs (e.g. #394, wating till after 2.1 is released) we should fix instead. So this is a questions of resources, for me.

Maybe you want to send in a PR to fix this, #444 and maybe #445? I would test and merge them. And If you need help around the core, it would be absolutely okay to send me your questions, or to ask for starting points.
