### ISSUE TITLE
Add all variables to serendipity_config_local.inc.php

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#469]
There are many variables one can set in `serendipity_config_local.inc.php`, see https://docs.s9y.org/docs/developers/code-primer.html#docs-initializing-the-framework-serendipity_configincphp-and-serendipity_config_localincphp

It would be nice to have all that variables documented in `serendipity_config_local.inc.php`, with their default values.

**Comment by garvinhicking** [comment]
Those variables are actually all set in serendipity_config.inc.php - if we add them to the local config as well, we would have to redundantly add them at two places and possibly change defaults at two places, which I don't really like. We can't ONLY put them to the local file, because it's not maintained in git. Soooooo....We might want to add a link to the documentation page in the config_local file instead? :-)

**Comment by th-h** [comment]
I don't think so - some variables aren't set in `serendipity_config.inc.php`, e.g. `$dashboard*Limit`. I'd like to add those, commented out, so you can see everything you can change.

The defaults that are set in `serendipity_config.inc.php` can and should stay there, I think.

**Comment by th-h** [comment]
After thinking some more, let's add a link to the documentation page to `serendipity_config_local.inc.php` and move all defaults to `serendipity_config.inc.php` that are not yet there (see PR 493 for example).
