### ISSUE TITLE
Please add the "last updated date" to the overview of plugins 

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#471]
It would be great to make it sortable as well.

**Comment by th-h** [comment]
The "last updated" date is not cached yet. We could add another row to the `pluginlist` table, or we use the `last_modified` (which holds the mtime of the local files - but we could repurpose it for columns where `pluginPath` is `online_repository`).

**Comment by ddeimeke** [comment]
Where does this page - http://spartacus.s9y.org/index.php?mode=bygroups_event_en - get its data from?

**Comment by yellowled** [comment]
It's read directly from the plugin files in `additional_plugins` by [emerge_spartacus.php](https://github.com/s9y/additional_plugins/blob/master/emerge_spartacus.php).

**Comment by th-h** [comment]
As we have all that information on Spartacus, let's just add a link to that. I think that's more feasible than to add lots of code to read and cache the date of the last update.

See #621. I think that would fix this request (as good as we can do, considering this issue is now more than two years old).
