### ISSUE TITLE
Implement responsive images

### ISSUE THREAD

**Issue by garvinhicking** [s9y/Serendipity#474]
Create an easy way for authors to pick a single image and make Serendipity automagically create specific thumnail sizes.

A template would need a way to preset valid thumbnail sizes, like: $serendipity['responsiveImageThumbnails'] = array(400, 720, 1080);

When inserting an image, through the "s9y-mediadb-XXX" (sth like that) ID reference to the thumbnail, a plugin can use markup functions to grep through the entry body and add the required HTML for image/srcset parameters, and generate (if not existing) all corresponding thumbnail sizes.

The plugin also needs to take care of parsing all existing blog entries to perform that action (like assigncategories does?). Maybe couple it with thumbnail regeneration (plugin hook?).

**Comment by onli** [comment]
c585f73f8cdf8070284d32548ff7c27b21d87eb4 is an initial approach. There are still a number of questions. @yellowled, I think those are mostly for you.

 1. In my current approach, I did not use the set thumbnail sizes. But I think understand now why that would be necessary - the original images can have different width, with thumbnails in different sizes + unknown container width it seems impossible to create a sizes-list that works, as we only can query over the viewport. Is that correct?
     1. We absolutely do need a sizes list with media queries, right? The browser can't just select the fitting one if we just give him a srcset and specify the images width?
 1. How shall we handle the difference between thumbnail and full size insert? So far, the user can chose whether to insert a thumbnail or the full width image. If it is a thumbnail, the width of it is configurable. Shall we then generate additional smaller thumbnails to make the original thumbnail responsive? How to combine that with the themes `responsiveImageThumbnails` setting?

> The plugin also needs to take care of parsing all existing blog entries to perform that action (like assigncategories does?). Maybe couple it with thumbnail regeneration (plugin hook?).

The plugin would already do that now, it hooks into backend_media_makethumb, which should be triggered when regenerating thumbnails. But doing that in the upgrader could be problematic, it could time out... I don't have a good idea yet how do that.

Problem is: When adding the srcset and pointing to nonexistant thumbnails, the browser happily switches to those if the media query says so, ending up showing no image at all. He does not use the falllback ;/

**Comment by yellowled** [comment]
> the original images can have different widths, with thumbnails in different sizes + unknown container width it seems impossible to create a sizes-list that works, as we only can query over the viewport. Is that correct?

I think so. The ultimate issue is that it is impossible (but also not intended) to pick just one set of `sizes` that will work in *any* layout. The idea is to provide a sensible list of available images and let the browser decide which one is the most appropriate for the current screen dimensions, layout dimensions and screen resolution (dpi).

> We absolutely do need a sizes list with media queries, right? The browser can't just select the fitting one if we just give him a srcset and specify the images width?

Well, technically, we can just use `srcset`. But that just gives the browser the screen width, which might not be enough. Think of grid/masonry layouts with a lot of images – it is definitely an advantage to provide the browser with the information how much of the viewport the image is supposed to take up; that's what `sizes` is for.

> Shall we then generate additional smaller thumbnails to make the original thumbnail responsive? How to combine that with the themes responsiveImageThumbnails setting?

Yeah, that's a tough one. We definitely **never** want to upscale images, just for quality reasons. I think we need some kind of rule  setting the smallest(?) `srcset` image in relation to the s9y thumbnail size or something. (I would actually like to check how the responsive images module for ProcessWire handles this.)

Either way – awesome that you already have a first version for this, this is **way** quicker than I expected!

**Comment by yellowled** [comment]
Not sure if this is helpful at all, but [this](https://github.com/conclurer/TextformatterSrcset/blob/master/TextformatterSrcset.module) is the ProcessWire module for responsive images, which I always took as a “good example how to do this”.

**Comment by yellowled** [comment]
> Well, technically, we can just use `srcset`.

To iterate on this, to *just* use `srcset` would be the minimum, but users should be able to *also* set `sizes`. I guess `srcset` only would be a good first step, but we do not want to limit the possibilities early on.

**Comment by onli** [comment]
> I guess srcset only would be a good first step, but we do not want to limit the possibilities early on.

I just played a little bit with that. To just not set sizes seems to work well, at least in 2k11 and with a full width image. With my test image it is one step too big (650px is the image width, it uses the 1200px thumbnail of a 1600px image, instead of the 800px thumbnail). I could accept that.

I will remove the sizes attribute for now. Then find logic to properly threat thumbnails - I guess just set the already generated responsive thumbnails into the srcset that are smaller than the original thumbnail. And add a set 'half of thumbnail' responsive thumbnail step.

Giving themes the option to optionally set a sizes element should then be not too hard - use the set sizes instead of the relative sizes if the theme sets the sizes option. Use a naming scheme to detect whether the correct thumbnails were generated.

> Either way – awesome that you already have a first version for this, this is way quicker than I expected!

Thanks! Serendipity is great for building this, it already had the thumbnail creation hook, the ML seems to just work with multiple thumbnails for one image, and most of what else is needed exists already in functions_images. And the mechanism we already had mostly figured out in Essen.

**Comment by garvinhicking** [comment]
This is so awesome! Loving the progress on this and ALL the other things that are flowing in at the other places -- Thanks to all, and many kudos to @thh :)

**Comment by onli** [comment]
Thanks Garvin :)

The last commit enhances this: If a thumbnail was inserted initially, it will no longer create an srcset with all of the images, but just use the images smaller than the thumbnail. Of that there is now always at least one: half of the thumbnail width. That's also added if the big image is inserted.

One problem: the smaller images are not always smaller in file size. I just had a 1600px image with 200kb, and the 1200px version had 500kb:

```
onli@Fallout:~/Serendipity.git$ du -sh /mnt/s9y_dev/uploads/skyrim_guardnative.* 
72K     /mnt/s9y_dev/uploads/skyrim_guardnative.1X.serendipityThumb.jpg
256K    /mnt/s9y_dev/uploads/skyrim_guardnative.2X.serendipityThumb.jpg
508K    /mnt/s9y_dev/uploads/skyrim_guardnative.3X.serendipityThumb.jpg
20K     /mnt/s9y_dev/uploads/skyrim_guardnative.halfThumbnail.serendipityThumb.jpg
168K    /mnt/s9y_dev/uploads/skyrim_guardnative.jpg
40K     /mnt/s9y_dev/uploads/skyrim_guardnative.serendipityThumb.jpg
```

If someone can confirm this, I'll open a separate separate. We probably use wrong or suboptimal settings in the thumbnail creation.

**Comment by yellowled** [comment]
Some things I noticed while testing this:

* When I upload an image with the plugin installed, I get the “Creating thumbnail” message 5 times. Not sure if that's related.
* If I insert the image in an entry and hit “Preview”, the image preview shows a broken image. It does, however, already use the reponsive images markup. (I think that's related to the errors below.)
* I'm not sure whether responsive images are supposed to have `width` and `height` attributes or if it's even a bad thing. Most of the examples out there omit them.
* The markup includes a `0w` case, which I'm pretty sure we can skip. ;)
* I'm not a fan of the 1X, 2X, 3X infixes. Those are usually used for HDPI resolutions, which is not what they represent here. Maybe we could just infix the width in px?

Most importantly, though, I get some error messages for [my test case](http://s9y.netzgestaltung.net/archives/55-Responsive-images.html) that I don't really understand.
```
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.
Dropped srcset candidate "/uploads/tortoise.serendipityThumb.jpg"
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.
Dropped srcset candidate "/uploads/tortoise.halfThumbnail.serendipityThumb.jpg"
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.
Dropped srcset candidate "/uploads/tortoise.serendipityThumb.jpg"
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.
Dropped srcset candidate "/uploads/tortoise.halfThumbnail.serendipityThumb.jpg"
55-Responsive-images.html:71 GET http://s9y.netzgestaltung.net/uploads/tortoise.3X.serendipityThumb.jpg 404 (Not found)
```

**Comment by yellowled** [comment]
> One problem: the smaller images are not always smaller in file size.

Mine are. However, if you rename a file after uploading it (which I did), the thumbnails (can we find a different name for the versions of the srcset? thumbnails is confusing.) are not regenerated for the renamed image.

**Comment by yellowled** [comment]
> Most importantly, though, I get some error messages for my test case that I don't really understand.

Interesting: After I re-uploaded the image with the proper name to the `/uploads/` root directory (not a subdirectory), it works just fine …

**Comment by yellowled** [comment]
Also, it did not create a `0w` this time.

> With my test image it is one step too big 

Pretty sure that's because of the missing `sizes`. I uploaded a 1920x1080 image; the smaller versions generated are 480x270, 960x540 and 1440x810 (which seem very reasonable values, by the way). However, the markup is

```
<img class="serendipity_image_center" width="1920" height="1080" srcset="/uploads/tortoise.jpg 1920w,/uploads/tortoise.3X.serendipityThumb.jpg 1440w,/uploads/tortoise.2X.serendipityThumb.jpg 960w,/uploads/tortoise.1X.serendipityThumb.jpg 480w,/uploads/tortoise.serendipityThumb.jpg 200w, /uploads/tortoise.halfThumbnail.serendipityThumb.jpg 100w" src="/uploads/tortoise.jpg" alt="A tortoise">
```
1. 200w and 100w are redundant
2. The `src` attribute should not contain the largest, but the smallest version of the image for performance reasons.

But this is still an *excellent* step towards a good solution, @onli. Great work!

**Comment by onli** [comment]
Thanks!

> Pretty sure that's because of the missing sizes. 

Yes, it is because the browser is not using the container width but the viewport width to determine which image to pick. Proper ttheme-picked `sizes` will help here.

> the thumbnails ... are not regenerated for the renamed image.

Oh, is the thumbnail normally linked to the image via the DB, and the new ones are only linked via the name, thus missed when renaming? Will have a look.

> can we find a different name for the versions of the srcset?

I used responsive thumbnails vs default thumbnail :)

> 200w and 100w are redundant

Why? Probably hard to see, but in your case the 200w one is `name.serendipityThumb.jpg` and has the configured thumbnail width, and the other is `name.halfThumbnail.serendipityThumb.jpg` and has half of that.

> The markup includes a 0w case, which I'm pretty sure we can skip. ;)

I hope we will stumble over the bug triggering this soon. Did not see it yet.

> When I upload an image with the plugin installed, I get the “Creating thumbnail” message 5 times. Not sure if that's related.

Absolutely. It is because he is really creating 5 different thumbnails. We could patch the core to emit only one message, but currently that still is useful.

> 'm not sure whether responsive images are supposed to have width and height attributes or if it's even a bad thing. Most of the examples out there omit them.

I think we will need them. They make it easy to implement the 'insert thumbnail' vs 'insert full size image' functionality of the core. And the plugin is now using the width value to decide which srcset options to generate.

> I'm not a fan of the 1X, 2X, 3X infixes. Those are usually used for HDPI resolutions, which is not what they represent here. Maybe we could just infix the width in px?

Yes, we can switch that.

>     The src attribute should not contain the largest, but the smallest version of the image for performance reasons.

Which performance reasons? In my tests, the browser is not fetching the one in src if a srcset is present and selecting another, at least FF is not. Also, the smallest is really small, if a browser is falling back to src because srcset is not working it will look really bad. I would prefer to keep it like it is now (which is how s9y did it before).

> > One problem: the smaller images are not always smaller in file size.
>
> Mine are.

Which file sizes are you ending up with? @bauigel, is that working for you (I remember you played with the imagemagick parameters once, right?)?

**Comment by yellowled** [comment]
> is the thumbnail normally linked to the image via the DB, and the new ones are only linked via the name, thus missed when renaming

I don't know, but in this case, it's an issue because the `srcset` versions are not generated at all for the renamed image, which means that the image will generate some 404s.

> Probably hard to see, but in your case […]

I assume they will never be used because resolutions < 200px or 100px in the wild probably do not support responsive images at all. They should get the fallback image, see below. (About the only devices I can think of here are “feature phones” and maybe smart watches, which most likely have HDPI displays, so 2x.)

> We could patch the core to emit only one message

I think that's a good idea, but it most certainly is okay to leave it for the time being.

> Which performance reasons?

Large images will take longer to load, eat up more data etc. It is very likely that the browsers that do not support `srcset` at all and will thus get the `src` fallback are on small, old and/or mobile devices.

It's what the [RICG demos](https://responsiveimages.org/) suggest by using `small.jpg` in the `src` attribute (if at all). It is the intended use of `src` in responsive images. I agree that they should not be *too* low quality, but if I upload a 1080p photo, that should *not* be the fallback size.

> I think we will need them.

I'm pretty sure it's not bad to have them, so it should not matter.

> Which file sizes are you ending up with?

```
29K tortoise.1X.serendipityThumb.jpg (480x270)
88K tortoise.2X.serendipityThumb.jpg (960x540)
169K tortoise.3X.serendipityThumb.jpg (1440x810)
2.5K tortoise.halfThumbnail.serendipityThumb.jpg (100x56)
246K tortoise.jpg (1920x1080)
7.1K tortoise.serendipityThumb.jpg (200x113)
```
And at least to my eyes, the 7.1K thumbnail is still pretty good quality.

**Comment by th-h** [comment]
>> When I upload an image with the plugin installed, I get the “Creating thumbnail” message 5 times. Not sure if that's related.
>
> Absolutely. It is because he is really creating 5 different thumbnails. We could patch the core to emit only one message, but currently that still is useful.

Perhaps we could add something about the size of the thumbnail(s) that is/are generated? So the messages would make more sense and aid in debugging, if necessary,

**Comment by yellowled** [comment]
By the way, we will want to add a polyfill here. IE/Edge support for this is [still weak](http://caniuse.com/#feat=srcset). [picurefill](https://github.com/scottjehl/picturefill) is kind of the gold standard here, but since it also supports the `<picture>` element (which we currently have no way/plans to support), we might want to go with [respimage](https://github.com/aFarkas/respimage) instead. (I have already used respimage, it works like a charm, although it looks unmaintained. [lazysizes](https://github.com/aFarkas/lazysizes) could also be an option.

**Comment by onli** [comment]
> ```
>29K tortoise.1X.serendipityThumb.jpg (480x270)
>88K tortoise.2X.serendipityThumb.jpg (960x540)
>169K tortoise.3X.serendipityThumb.jpg (1440x810)
>2.5K tortoise.halfThumbnail.serendipityThumb.jpg (100x56)
>246K tortoise.jpg (1920x1080)
>7.1K tortoise.serendipityThumb.jpg (200x113)
>```
>
> And at least to my eyes, the 7.1K thumbnail is still pretty good quality.

Yes, your filesizes look good. But my bad results are repeatable... I will move this to its own issue.

> Perhaps we could add something about the size of the thumbnail(s) that is/are generated?

Yes, if we keep it at multiple messages that would be necessary. Let's revisit that later.

> By the way, we will want to add a polyfill here.

Not sure the polyfill is necessary, the fallback behaviour should just restore how it works currently, no? But if it is small enough.

> I don't know, but in this case, it's an issue because the srcset versions are not generated at all for the renamed image, which means that the image will generate some 404s.

I had a look at the rename function and noped out of fixing that (https://board.s9y.org/viewtopic.php?f=3&t=21185) and adding the renaming of the responsive thumbnails. I will now try a re-implementation of the renaming functionality first.

**Comment by yellowled** [comment]
> Not sure the polyfill is necessary, the fallback behaviour should just restore how it works currently, no? But if it is small and easy enough...

Not if we have a low quality fallback img, which we should *at least* have as an option.

I can only speak for respimage; that requires adding a tiny piece of minified JS to the corresponding frontend hook and nothing else. Given the fact that even recent Edge versions do not support this, I'd say it's worth adding the polyfill.

**Comment by yellowled** [comment]
Just stumbled across another bugged output in my dev blog.

```
<img class="serendipity_image_left" width="200" height="160" srcset="/uploads/ w,/uploads/.3X.serendipityThumb. 0w,/uploads/.2X.serendipityThumb. 0w,/uploads/.1X.serendipityThumb. 0w,/uploads/.serendipityThumb. 0w, /uploads/.halfThumbnail.serendipityThumb. 0w" src="/uploads/artikel/veggies.serendipityThumb.jpg" alt="Veggies">
```
Perhaps the most interesting part of this is that this is the last of a group of images, and the other eight images in that group have *not* been transformed to responsive images. Also, this is an old entry that has not been re-saved or edited.

**Comment by onli** [comment]
@yellowled Does that bug still exist with the current git master? If yes, could you make a gist with the whole test entry?

**Comment by yellowled** [comment]
Tested again in recent git `master`, [test entry](http://s9y.netzgestaltung.net/archives/59-Responsive-images-revisited.html) and [src gist](https://gist.github.com/yellowled/0430cc9d409e678106f8cecdf09e7ceb) (note that I'll give up the uberspace containing my dev blog in a few weeks, so this link won't work very long).

Here's what I noticed:

* After uploading the image to the media db, the first thing emitted is a stray, unformatted `/path/to/ image/on/webspace.jpg`
* The “Creating thumbnail” msg is still emitted 5 times.
* Side note: I noticed that the image was not the most recent one in the media db. Apparently, uploading the new image(?) also reset (?) the upload date for **four** other images that were already in the media db (might be connected to the msg being emitted *five* times?), but definitely *not* uploaded today.
* The image is no longer broken in the preview. 👍 
* [This entry](http://s9y.netzgestaltung.net/archives/31-Lightbox-Test,-grosse-Galerie.html) still has the weird `srcset` with the `0w` images, but I haven't re-saved that entry, either.

I'm also still convinced that the original image should *not* be the fallback, or that it should at least be an option to use a low-quality fallback image. Also still thinking that we do not need 200w *and* 100w (but one of them for feature phones and as said low-quality fallback).

File sizes:

```
$ ls -lha frog.*
58K Jun  4 19:05 frog.1X.serendipityThumb.jpg
189K Jun  4 19:05 frog.2X.serendipityThumb.jpg
404K Jun  4 19:05 frog.3X.serendipityThumb.jpg
4.6K Jun  4 19:05 frog.halfThumbnail.serendipityThumb.jpg
580K Jun  4 19:05 frog.jpg
16K Jun  4 19:05 frog.serendipityThumb.jpg
```
Did I forget something?

**Comment by onli** [comment]
No, that's fine :)

http://s9y.netzgestaltung.net/archives/31-Lightbox-Test,-grosse-Galerie.html looks completely broken. Seems like there are issues with multiple images (and repeated images) being on one line.

**Comment by yellowled** [comment]
> Seems like there are issues with multiple images (and repeated images) being on one line.

I should note that it can actually be important that they are on one line (in the source code) if they are aligned using `display: inline-block` (which is not used here now, but I think *was* at some point). ([CSS tricks article](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) on that)

**Comment by onli** [comment]
That should be fixed now. I improved the replacement logic to work also when images are on the same line.

https://github.com/s9y/Serendipity/commit/a920a3aa67152c0470a4b12ba54b0e24ec8534d5 fixes the 0w bug, at least in my installation. There the problem was that the upload folder was not properly detected. That commit also introduces logic to set a specific breakpoint for a thumbnail width, I think that's what we need to create a proper srcset.

**Comment by yellowled** [comment]
If so, it does not “work backwards”. For my [lightboxed gallery](http://s9y.netzgestaltung.net/archives/31-Lightbox-Test,-grosse-Galerie.html) test case, it now only addresses the *first* image in the entry (used to be the last). Also, the source code still looks weird.

```
<div class="gallery clearfix"><a rel='magnificPopup[31]'  class="serendipity_image_link"   href='/uploads/artikel/steak.jpg'><!-- s9ymdb:68 --><img class="serendipity_image_left" width="200" height="160"   srcset="/uploads/ w,"   src="/uploads/artikel/steak.serendipityThumb.jpg"  alt="Steak"></a><a rel='magnificPopup[31]'  class="serendipity_image_link"   href='/uploads/artikel/sushi.jpg'><!-- s9ymdb:66 --><img class="serendipity_image_left" width="200" height="160"   srcset="/uploads/ w,"   src="/uploads/artikel/sushi.serendipityThumb.jpg"  alt="Sushi"></a><a rel='magnificPopup[31]'  class="serendipity_image_link"   href='/uploads/artikel/veggies.jpg'><!-- s9ymdb:67 --><img class="serendipity_image_left" width="200" height="160"   srcset="/uploads/ w,"   src="/uploads/artikel/veggies.serendipityThumb.jpg"  alt="Veggies"></a>[…]</div>
```
Again, I did *not* re-save that article so far. (The rest of the images are not modified by the plugin like the second one.)

**Comment by onli** [comment]
Yes, you need to delete the images and upload them again to have the right thumbnail sizes created. Or you let it as it is and I tackle thumbnail creation next?

**Comment by yellowled** [comment]
I can do whatever. Since I'm giving up that domain/web space, that dev blog will only be available until the end of the month anyway. Not sure how I'll handle dev blogs after that. So I guess it would be good to leave it up as a test case.

**Comment by onli** [comment]
Note: It needs to be tested whether the thumbnails get generated when the image gets downloaded, not uploaded (that came up on the s9y meeting via testing by bernd).

**Comment by onli** [comment]
On second thought, if the thumbnail is not there nothing there the plugin will not set a thumbnail, so that's not as critical as I thought. I'll close here and we should react to proper bug reports, if there is more to do.

**Comment by onli** [comment]
I have an example where this does not work great. https://www.onli-blogging.de/1823/Wenn-Android-bei-der-Smartwatch-Missing-Feature-Watch-anzeigt.html. The original image size is 625W. The plugin picks the 400W thumbnail but nothing else into the srcset. Since width is still set to 625 this gets blurry.

I think the right behaviour would be to add the original at a breakpoint above the biggest thumbnail, right?

**Comment by yellowled** [comment]
Well, it depends. I assume the issue here is that there are no suitable images sizes available to generate smaller versions, so the "error" is technically not uploading a large enough image. :)

In an ideal world, you'd *always* have a "starting image" large enough to generate even the largest `srcset` image. So if your `srcset` is `1.jpg 320w, 2.jpg 768w, 3.jpg 1440w`, your uploaded image would be at least 1440px wide. This is likely to happen in a lot of cases since most users tend to upload images way larger than used later.

What should happen if the image used is *smaller* is kind of a preference thing, I'd say. It might even be too complicated for a plugin to figure out, I guess. So if the uploaded image is 625px wide and the first "use a larger version" point of `srcset` is for instance 768px (i.e. if the uploaded image is just big enough to generate the smallscreen version), I would probably not use `srcset` at all and just emit a "normal" `<img src="…" alt="…" />`.

The reasoning behind this is that you should never scale up images. They will always look bad, and having to scale images is extra work for the browser.

**Comment by onli** [comment]
I'm now adding the image to the srcset in those cased. Most of the time that will be the same as not having a srcset at all.
