### ISSUE TITLE
Upgrader should update plugins

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#477]
The upgrader should first update the installed plugins before updating the core.

**Comment by onli** [comment]
That's complicated.

We do not have the one function that updates all plugins. I think we don't even have one function that updates one plugin, instead spartacus downloads the new plugin files and then possible upgrade tasks are run when the plugin configuration is opened afterwards. Our "update all plugins" button is a javascript cheat because of that.

In the upgrader it's too late to react. We can detect that plugin upgrades are available - I just pushed a commit that shows a warning to the user in that case - but the user can not pause the update anymore, the files are already on his system. If the user opened the plugin configuration the upgrader opens instead.

I see only one place for this functionality: the autoupdate plugin. Before unpacking the release it can check whether plugin updates are available and direct the user to the plugin update screen. I will test an implementation of that now.

**Comment by onli** [comment]
Done in https://github.com/s9y/additional_plugins/commit/74d3cbd23707367716bf5f60a660cc8cbd163170. This will work from 2.4-alpha on, I think that was when the plugin update check was introduced which is reused here.
