### ISSUE TITLE
Configuration blocks in Settings/Configuration should be expanded when serendipity_editor.js can't be loaded

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#479]
The configuration blocks in Settings/Configuration should be expanded by default when `plugin/admin/serendipity_editor.js ` can't be loaded, so you can fix wrong config settings: see #478 for an example.

**Comment by yellowled** [comment]
I can not reproduce this, so it might be specific to @th-h 's blog/setup. The “open variable“ is that his dev blog runs on PHP 5.4, mine is on PHP 7.0 …

**Comment by th-h** [comment]
The underlying bug (#478) most probably, but I don't see how that should apply to the JS issue ... We'll see. :-)

**Comment by yellowled** [comment]
Well, technically, this particular JS is being compiled from a Smarty template so that it can use certain variables, lang constants etc. I guess it would be possible that the compiled JS is somehow broken? Not really my expertise, but since I can't even reproduce the triggering error …

**Comment by th-h** [comment]
Steps to reproduce (for the .js behaviour, not for the underlying bug):

1. Open the backend configuration screen (`/serendipity_admin.php?serendipity[adminModule]=configuration`). Blocks are expendable. Switch to another screen.
2. Make `templates/2k11/admin/serendipity_editor.js.tpl ` unavailable (`chmod 000` should do the trick).
3. Delete the template cache (`rm -r templates_c/*` works, but may be a bit ... rough).
4. Go to Settings/Configuration. Nothing works - blocks don't extend.

I.e. is it possible to make that work without .js? Any kind of fallback?

**Comment by onli** [comment]
The issue here was simply one of relying on javascript. @th-h, your steps to reproduce work, I did not even have to delete templates_c, ust sabotage `serendipity_editor.js.tpl` somehow.

The scheme worked so far by generating the html with the classed that hide the configuration. The javascript was used to clock on the first config block, to make it visible. I now turned it around: The generated html uses the css classes to show them all by default, the javascript is used to hide all but the first. 

This might still need some testing to work as intended with storing the order.
