### ISSUE TITLE
Make comment subscriptions editable

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#490]
Readers can subscribe to entries to get notifications for every new comment. But some readers change their mail address, and some spam bots subscribe, too, so it would be nice if an admin / chief editor could change the subscription state.

The state is tracked by the `subscribed` column in the `serendipity_comments` table, but the backend _comments_ module lacks support to (un-)set this state.

Please add the necessary logic and UI elements.

**Comment by stephanbrunker** [comment]
Same issue here as in #531 . This is in the area of the Blog subscription. Because a blog subscription list can have a lot of entries and to prevent the notifications to be classified as SPAM, you have to take care of the bounce messages. So, I have to create a subscription manager which includes the comment subscriptions and the blog subscriptions. It is just HUGE in its entirety, so I am going to need a few weeks to publish a feature-branch for testing. 

And I cannot solve everything at once. For example, create the messages in the language of the user seems to be quite difficult because at the time of its creation the author is logged in the backend with another language and all the language constants are set. So it is only default lang for now.

**Comment by onli** [comment]
Hi @stephanbrunker, cool that you continue to work on that. I several times now pushed features that were just english, and had to be made translatable in a second step. Especially during the alpha I really think that would be okay.

**Comment by stephanbrunker** [comment]
Included in the [feature_subscription](https://github.com/s9y/Serendipity/tree/feature_subscription) branch
