### ISSUE TITLE
Default .htaccess rewrite configuration collides with plugin documentation URLs

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#521]
Plugins may have a local documentation of the form `documentation.html` or `documentation_XX.html`, with *XX* to specify the language.

The default `.htaccess` rewrite configuration includes this rewrite rule:
`RewriteRule (.*\.html?) {indexFile}?url=/$1 [L,QSA]`

That rule will trigger for the local documentation files and rewrite them to a call to `index.php?url=...`, triggering a 404 error.

Some (!) plugins solved this problem by including their own `.htaccess` file like this:

    <Files .htaccess>
    Allow from all
    </Files>
    
    <IfModule mod_rewrite.c>
    RewriteEngine Off
    </IfModule>

Those files are present - at least - as follows (there are about a dozen more):
* plugins/serendipity_event_lightbox/.htaccess
* plugins/serendipity_event_staticpage/.htaccess
* plugins/serendipity_event_staticpage/img/.htaccess *[1]*
* plugins/serendipity_plugin_twitter/.htaccess
* plugins/serendipity_event_freetag/.htaccess

*[1] I don't think that makes any sense at all as the (identical) file `plugins/serendipity_event_staticpage/.htaccess` will suffice.*

I don't think we should go down that path ... Instead the rewrite rules should exclude plugin documentation.

I propose to
* add a new rule immediately before the one quoted above:
`RewriteRule ^(plugins/.+/documentation.*\.html?) $1 [L]`
* remove all those `.htaccess` files (perhaps short of the ones in `/img/` folders - are they needed there?

Otherwise, we'd have to add `.htaccess` files like those at least to all plugins with a local documentation; that doesn't make sense. Or we add it at the `/plugins/` level? That would work, too.

What do you think?

(I refrained from submitting a PR because I'd like some review and a recommendation how to go on from here.)

Forum discussion: https://board.s9y.org/viewtopic.php?f=10&t=21432

**Comment by garvinhicking** [comment]
Yeah it would be better to have it in the central .htaccess, the rule you mentioned should be fine I think. A second .htaccess file in the plugins subdirectory doesn't sound so good.
However removing the .htaccess from current plugins would then mean they no longer show documentation on any Serendipity version released earlier. So I think we should keep those .htaccess file for some time.
And we need to add an upgrader task that upgrades the .htaccess file on migration, we should have a function for that already.

**Comment by garvinhicking** [comment]
I just committed a new regexp rule and upgrader task for this.

**Comment by th-h** [comment]
Thanks! :-)

I'm not sure if the upgrader task is quite right, though.

**Comment by JialuZhang** [comment]
@th-h 

In your configuration,

```
<Files .htaccess>
Allow from all
</Files>

<IfModule mod_rewrite.c>
RewriteEngine Off
</IfModule>
```

the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
This is because the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by garvinhicking** [comment]
The thing about this is that such code would be placed in a subdirectory.

However, the central .htaccess actually ENABLES rewriteEngine, so the subdirectory needs to disable it.

Example:
/path/to/documentroot/.htaccess contains RewriteEngine On
/path/to/documentroot/plugins/serendipity_event_example/.htaccess contains RewriteEngine Off

This is so that when you open a URL like http://example.com/plugins/serendipity_event_example/Test.html the actual "Test.html" file there would be resolved. However, the central .htaccess has a catch-all for any *.html link. So without disabling the rewriterules contained in the plugin directory, the HTML would not be served.

Actually within this issue, we added a central "documentation" rewriteRule that makes such disabling obsolete. But in some cases plugins might still need to disable rewrites on their own...
