### ISSUE TITLE
Feature request: Subscribe to comments

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#531]
It would be great to have the possibility of subscribing to comments (with Opt-In) without the need to leave a comment to a blog post.

**Comment by th-h** [comment]
We could add a checkbox or another button on the comment template for this ...

**Comment by stephanbrunker** [comment]
I am currently working in this area. It is not as easy as it seems, because the subscription data is stored in the comments table. You would have to essentially create an empty comment to subscribe and filter that out. Not nice, but doable. Option two: completely rework the storage of the subscribe data in it's own table to separate comments and subscriptions. Because of the huge impact, this seems unwise. Option three: I am working at an email subscription for the blog as a whole (notification for new articles) with a new subscriptions table, and it would be possible and relatively simple to add a new field articleID there to subscribe to an article only. 

It is just that this whole project is more massive than I thought, but I see what I can do here.
