### ISSUE TITLE
Array in rss.php not compatible with PHP 5.3

### ISSUE THREAD

**Issue by guillaumezin** [s9y/Serendipity#534]
Hello,

Would it be possible to change $allowed_versions = array('opml1.0', '0.91', '1.0',  '2.0', 'atom0.3', 'atom1.0'); instead of $allowed_versions = ['opml1.0', '0.91', '1.0',  '2.0', 'atom0.3', 'atom1.0']; line 25 of rss.php? This way it would stay compatible with PHP 5.x earlier than 5.4.

Thank you.

Best regards.

Guillaume

**Comment by onli** [comment]
Hi Guillaume

PHP 5.3 is not supported anymore. Not only by us, but also by PHP itself. It is insecure to run a version that old, since the PHP project does not provide security patches anymore.

Changing that line is of course possible, but in that context it would send the wrong signal. There is also the problem that we did not test with PHP 5.3, and there might be other areas that are broken, maybe with issues that are not immediately visible (e.g. wrong charsets landing in the database, silent data dismissal, stuff like that). 

The right solution is to upgrade to PHP 5.6, or better to PHP 7.0.

**Comment by guillaumezin** [comment]
You're right, I have convinced my sysadmin to upgrade my old Ubuntu 12.04 virtual machine to a more recent one
