### ISSUE TITLE
FEATURE REQUEST: Automatically set last-added folder when uploading media

### ISSUE THREAD

**Issue by manitu-opensource** [s9y/Serendipity#537]
[ FEATURE REQUEST, not a bug ]

What about automatically set ("select") the last-added folder when uploading media?

Background: When deleting cookies (when closing browser) all information about last-selected folder are lost. So I suppose most people doing the same would appreciate to auto-set the last-added folder (e.g. when using a structure like YYYY-MM or YYYY --> MM (as hierarchy).

Maybe you could opt-in this feature in a settings.

**Comment by onli** [comment]
How do you feel about remembering the last selected instead?

Using the last added folder feels a bit too intelligent to me, stuff like that can be unexpected. But remembering the last folder you uploaded an image to would be normal, and behave like when when we remember the image float type when adding an image to an entry.

**Comment by manitu-opensource** [comment]
As far as I know, the last selected folder get remembered already.

I wish this feature of the last added folder to be an option defaulting to off.

The last selected folder is, as I wrote, depending on a cookie. People (like me) deleting all cookies when closing browser cannot use that.

**Comment by onli** [comment]
It seems there was no consensus on implementing this. I think that my initial feeling that this is too surprising is indeed valid, and if we'd implement it it would be via a cookie (or alternatively local storage) - meaning it would not help you either way. Putting this into a config field in the database feels too complicated for this, to me.

I checked in #652 that remembering the last used directory works, and I'm gonna double-check now that it works with the different upload options.

If I'm judging this wrong please re-open. @manitu-opensource Please don't hesitate suggesting other improvement, I think this was open so long because no one wanted to react badly to a feature request :)
