### ISSUE TITLE
Latest release has broken Akismet calls in the spamblock plugin

### ISSUE THREAD

**Issue by fishnix** [s9y/Serendipity#538]
Hi!

It looks like the fix from https://github.com/s9y/Serendipity/pull/507 needs to make its way into a release.  

https://github.com/s9y/Serendipity/blob/2.1.1/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php#L556

It took me a while to track that one down!  😆 

Thanks!

**Comment by onli** [comment]
This is already in master, if I saw that right, and will be in the next release. Sadly we can't just make a new release right  now, there are too many things in an unfinished state (like my removal of the ACL system in the media library, which I need to patch back in, and the UTF8 mysql migration that is not tested enough; maybe that one could actually use a beta release though, one with proper warning.

**Comment by th-h** [comment]
> This is already in master, if I saw that right, and will be in the next release.

Which should have been released some time ago, I think.

> Sadly we can't just make a new release right now, there are too many things in an unfinished state (like my removal of the ACL system in the media library, which I need to patch back in, and the UTF8 mysql migration that is not tested enough; maybe that one could actually use a beta release though, one with proper warning.

We could - and should - do a patch release. In fact, I think, we should have done that month ago ...

There are some irritating bugs (Akismet is broken, spamblock_rbl|surbl don't work, comments are deleted when previewing while logged in, ...) which are fixed in master and _backported to 2.1_. We could do a 2.1.2 patch release, so new downloads and upgrades don't break plugins, and release 2.2 when we're ready (or 2.1.3 if we fix some more annoying bugs).

**Comment by onli** [comment]
Yeah, you are right. We should also in that point release fix spartacus by setting it to github, disabling netmirror, also via an upgrade task for existing installations.

**Comment by onli** [comment]
A upgrade task would not even be necessary. The mirror list in masters spartacus already does not list netmirror anymore. And the config option returns an array index. We would only have to prevent using a too high array index for the now smaller mirror list, which can be done directly in spartacus.

**Comment by onli** [comment]
https://github.com/s9y/Serendipity/commit/615591a7d97fb3716933717028a29b049a823f94 fixes spartacus in the 2.1 branch. What else needs to be backported for the point release?

**Comment by th-h** [comment]
0f9bfe3fda4259596de1a7dab9b8df86f4e65139 could be a candidate.

I don't know about d3e6a3ee3a94c0886c7fcb105dbd5293c55a54a7 - that's one of your commits. :)

**Comment by th-h** [comment]
5ad93297ed77cb34b04c52425af5763eab066705 (in `master`) and 615591a7d97fb3716933717028a29b049a823f94 (in `2.1`) differ. I think we should settle for one solution (e.g. cherry-pick the one from `master` to `2.1`, or change `master` to match `2.1`).

**Comment by onli** [comment]
https://github.com/s9y/Serendipity/commit/d3e6a3ee3a94c0886c7fcb105dbd5293c55a54a7 is new code, that bug is not in 2.1 :)

0f9bfe3 maybe. It is an UI bugfix, not really a code bugfix, those can lead to other bugs and maybe are not right for a point release. I'll cherry-pick it, but let's have a second look whether that works as expected.

**Comment by th-h** [comment]
> d3e6a3e is new code, that bug is not in 2.1 :)

I see. :)

> 0f9bfe3 maybe. It is an UI bugfix, not really a code bugfix, those can lead to other bugs and maybe are not right for a point release.

The change seems save enough, but I agree it has not been tested very thoroughly, as you don't encounter multiple errors in normal operation very often.

> I'll cherry-pick it, but let's have a second look whether that works as expected.

We could schedule it for an 2.1.3 oder 2.2 ... It's not urgent,

**Comment by th-h** [comment]
2.1.2 has been released yesterday.
