### ISSUE TITLE
Be fully compatible with 7.2

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#556]
We already fixed some issues, but we still need to make sure that we are fully compatible with 7.2

**Comment by hannob** [comment]
Two uses of deprecated each functions cause warnings:

1. smarty

PHP Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /home/hanno/websites/s9y.q2.re/htdocs/bundled-libs/Smarty/libs/sysplugins/smarty_internal_compilebase.php on line 75

This should probably be fixed by upgrading the bundled smarty to the latest version (which also fixes a security issue).

2. In plugin_api.inc.php

Notice: The each() function is deprecated. This message will be suppressed on further calls in /[path]/include/plugin_api.inc.php on line 1123.

Appears when doing a fresh installation from current git on the start page.

**Comment by onli** [comment]
I spent some time on this. I moved my est installation with the current master over to PHP 7.2 and fixed all reported issues. Please reopen if additional issues pop up.

**Comment by hannob** [comment]
What's the expected timeframe when these fixes will end up in a release?

PHP 7.1 is already nearing its end of life, with support ending in december (with extended security support for a year longer). I think it'd be good to have a release properly (and warning free) working with 7.2 before that. Which could either mean backporting these fixes to 2.1 or having a 2.2 version soon.

**Comment by onli** [comment]
The current plan is to have a first beta release of 2.2 next week
