### ISSUE TITLE
uri-rewrite for srcset (functions_rss.inc.php)

### ISSUE THREAD

**Issue by bauigel** [s9y/Serendipity#585]
I updated my weblog to current git-checkout to try some of the new features and found a bug in rss-generation.

The plugin "responsive image" use srcset within the img-tag and my rss-readers (Fiery Feeds for iOS, Tiny Tiny RSS in browser) can not resolve the relative uri. @onli gave me the hint, that line 85 and following of functions_rss.inc.php seems to be the problem, because srcset is not included in url-rewriting.

I tried to modify the two lines like the following and the replacement seems to work so far, the images are shown again in rss.

Any ideas what else could be necessary to be modified or is this the only one?

```
if ($serendipity['serendipityHTTPPath'] == "/") {
      $pattern = '@(href|src|srcset)=(["\'])/([^/][^"\']*)@imsU';
} else {
      $pattern = '@(href|src|srcset)=(["\'])' . preg_quote($serendipity['serendipityHTTPPath']) . '([^"\']*)@imsU';
}
```

**Comment by bauigel** [comment]
OK, it doesn't fully fix what i hoped. The fix just replace the first appearance of the path in srcset, not everyone. :-/  Because of this, some images are loaded in RSS-Reader and some not because i get a 404.

     <img srcset="https://bernd.distler.ws/uploads/2018/09/Kanada/12/2018-09-12_09-39-07.jpg 1778w,/uploads/2018/09/Kanada/12/2018-09-12_09-39-07.1200W.serendipityThumb.jpg 1600w,/uploads/2018/09/Kanada/12/2018-09-12_09-39-07.800W.serendipityThumb.jpg 1200w,/uploads/2018/09/Kanada/12/2018-09-12_09-39-07.400W.serendipityThumb.jpg 600w" src="https://bernd.distler.ws/uploads/2018/09/Kanada/12/2018-09-12_09-39-07.serendipityThumb.jpg" alt="" referrerpolicy="no-referrer">

**Comment by onli** [comment]
Hi @bauigel. Yeah, the regex as it is in https://github.com/s9y/Serendipity/blob/master/include/functions_rss.inc.php#L85 is not properly designed for the task. The problem is that `[^"\']*` will match all other characters after the first /, including the other referenced images. That's why the replacement is done once.

We would need a regex that replaces the leading / and ignores the rest, maybe by searching for `,/`.

It might be safer and better to use a HTML parser for this, like https://github.com/paquettg/php-html-parser. If it works as I expect with that one could select all `img` elements, get the srcset, change the relative links to absolute links and then return the modified HTML. What do you think?

**Comment by bauigel** [comment]
I'm not sure if we really need a parser (even i really don't know how complicate it would be to implement). Maybe it would be easier to include another replace with a separate regex just for the imgsrc.

**Comment by onli** [comment]
I pushed a fix for this into the master, plugin version 0.5. Could you have a look whether that works as well with your configuration?

**Comment by bauigel** [comment]
Tried it last weekend with several postings and images. Seems to work good, all images are shown within web-interface (tiny tiny rss) and iOS client (Fiery Feeds). 👍 
I close this bug. Maybe i'll open another one, if i find something.
