### ISSUE TITLE
Please make spartacus site HTTPS

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#592]
The current source for manual plugin downloads is the spartacus webpage:
http://spartacus.s9y.org/

Both the webpage and the downloads are HTTP. I think these days everyone should use HTTPS by default, but for software downloads the risk is particularly high.

**Comment by yellowled** [comment]
I seem to remember some sort of blocker for that due to the server that it's running on which the dev team unfortunately has no direct access to. Maybe that has changed in the meantime, it's been a while since we migrated most of our infrastructure.

@garvinhicking Please remind me, is Spartacus on Jannis' server or did we move it to Uberspace? (Uberspace should have Let's Encrypt available, but that may depend on which Uberspace version we're on …)

**Comment by th-h** [comment]
Spartacus seems to be hosted at sourceforge:
```
thh@thangorodrim:~$ host spartacus.s9y.org
spartacus.s9y.org is an alias for vhost.sourceforge.net.
```

**Comment by onli** [comment]
I agree that all of this should use https, the webpage as well as the repo. I know that we already use letsencrypt with uberspace for parts of our infrastructure, I  get notification mails - the blog is hosted there (the forum might be on a different uberspace?). I think the last time spartacus was the one thing we did not want to move over just yet.

We will need garvin for this.

**Comment by th-h** [comment]
Spartacus moved to Uberspace. After the DNS changes have propagated. it will have HTTPS by default.
