### ISSUE TITLE
Auto-update to 2.3.0 fails due to integrity test failures

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#631]
Upgrades from 2.1.x to 2.3.0 with `serendipity_event_autoupdate`  fail due to integrity check failures with
* templates/next/font/fontello.svg
* templates/2k11/admin/font/fontello.svg
* bundled-libs/zendframework/zend-db/phpcs.xml
* bundled-libs/simplepie/simplepie.inc
* bundled-libs/katzgrau/klogger/phpunit.xml

This seems due to a [change from two years ago](https://github.com/s9y/Serendipity/commit/be3df87b975ac843dbbc8d413e6ab82cc2128093) in `serendipity_FTPChecksum` (changing from binary to text mode). The new release uses the new code from the master/2.3-branch to generate the checksums, but `serendipity_event_autoupdate` has to use the old, installed code from the 2.1 branch.

See [the forum thread](https://board.s9y.org/viewtopic.php?f=1&t=24492).

That's not easy to fix; one could do a 2.1.7 release with updated checksum code and manually changed checksums so the old code will validate; after that, auto-updates will work again.

Another suggestion would be to add a switch to disable integrity checking for one (the next) run of the auto-updater; I think I'd prefer that. See @mattsches [suggestion](https://github.com/mattsches/additional_plugins/commit/c8b368cd89ee3fed8a8a0e92463c2cc981faa430).

@onli, @garvinhicking - what do you think?

**Comment by onli** [comment]
A 2.1.7 would not help much in my eyes, because the 2.3.0 is a stable release. So autoupdate would not select the 2.1.7 ever.

Instead of the configuration option, how about disabling the integrity check generally when going from a version < 2.3.0 to a version >= 2.3.0? The plugin should already stop before when there is an error unpacking the zip.

Alternatively maybe even a button on the upgrader to continue anyway when the checksum failed?

If both are not possible a config option would be fine.

**Comment by th-h** [comment]
See PR s9y/additional_plugins#103.

**Comment by th-h** [comment]
Fixed by s9y/additional_plugins#103.

**Comment by stefanhorning** [comment]
Same error still happens when upgrading from 2.1.5 to 2.3.2
