### ISSUE TITLE
Unclear use of AuthUser language

### ISSUE THREAD

**Issue by stephanbrunker** [s9y/Serendipity#640]
As in issue #635 , i am working my way through the language settings. But it is unclear out of the code what was intended if a user is logged in. Currently, it is (or was) possible to log in, change the language in the frontend, and then enter the backend which is switched to another language too. But this scrambles the multilingual plugin, because the default article in the blog's default language is then overwritten with this different language which is now seen as the default language. 

My question simply is: if a user is logged in, should his language setting in the database have priority over anything else (which means that it is not possible to change the blog language anymore) or should his setting only be a fallback (in frontend and/or backend) if no explicit language is given from the user (e.g. GET, POST or that saved in COOKIE) ?

And how and when should the user setting in the database be saved? On the first look, I couldn't find where the 'lang' var is set, but I can see in my database that it is set.

This is a kind of strategic decision which I cannot make ...

**Comment by onli** [comment]
Hi. For context, I'm not deep into the language functions of s9y. Listen to what @garvinhicking has to say. But my impressions:

> should his setting only be a fallback (in frontend and/or backend) if no explicit language is given from the user (e.g. GET, POST or that saved in COOKIE) ?

This. Because that way, you can implement a preview functionality of the multilanguage plugin.

> And how and when should the user setting in the database be saved?

That's part of the personal configuration of the user, no? Thus it is part of include/tpl/config_personal.tpl, and saved into the database with `serendipity_set_user_var` in `include/admin/personal.inc.php` when saving the configuration. See `users.inc.php` for the user creation process, and `installer.inc.php` in the same folder for user creation during the installation.

**Comment by yellowled** [comment]
About the only things I feel I can contribute here:

* I find it perfectly valid to (want to) have different languages in the frontend and in the backend.
* I would never use the language set in the browser or extrapolatet from the IP or something for any of this (since there are people who use different languages than the country they live in or a VPN).

**Comment by stephanbrunker** [comment]
I think the question is answered. I reconstructed the language deciding process such that it uses POST 'user_language' first, then GET 'user_language', save these user decisions into COOKIE and SESSION, and if these are not set, try Browser language negotiation if the boolean is set in the db, and as fallback the blog default language which is overwritten by the users default language if that is different. And as fallback-fallback 'en'.
