### ISSUE TITLE
CKeditor eating figcaption on iPad

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#660]
In https://github.com/s9y/Serendipity/commit/b614ed5d07d8d2bc490836dbd40daa2acce68c9d a small config change stopped CKeditor from removing the ficaption used as image caption holders in current s9y version. It seems like that works perfectly fine in Firefox, but when using Safari on the iPad the figcaption still gets removed/transformed into regular p tag.

I got this as a bug report. But can't properly test it since I don't have the needed hardware. Is this really a browser incompatibility, or is something else going wrong here? Can we reproduce this issue? @yellowled ?

**Comment by yellowled** [comment]
@onli I can *not* reproduce this using s9y 2.3.2 in Safari on an iPad Air 2 running iPadOS 13.2.2. However, there are two caveats here:

* Since I do not have a test blog right now, I created a test entry in my production blog. I only saved this as a draft, but never published it. It might be that “something happens” when publishing. I wouldn't know since I typically don't use CKE.
* Of course, this may have been different in a previous version of iPadOS or iOS. (There is no way to update Safari on iOS without updating iOS, it's always bundled with a specific iOS version.) I don't have a means to test earlier versions of i(Pad)OS, since I keep my devices up to date.

So it's not a 100% “works fine”, also given the fact that the bug report might use a different CKE config than I did. But unless this comes up again, I would assume that it's not an issue.

**Comment by th-h** [comment]
Closed as not reproducible. - Please reopen if the problem persists (and please try to add more information - steps to reproduce - in that case).

**Comment by onli** [comment]
Okay, I got asked again whether this issue was addressed and sued this to ask for more information. The user writes:

> Ich gehe in die Mediendatenbank, klicke das gewünschte Bild an, fülle wie am PC auch die Oberfläche aus (siehe Screenshot oben rechts), klicke Fertig an, bekomme dann aber nicht den gewünschten BT in kleinerer, sondern in normaler Schrift und zudem als Flattersatz.

The screenshot just showed him using the ML in the entry editor.

The hardware and OS in question is:

I-Pad Pro 13.5.1

**Comment by onli** [comment]
![image3](https://user-images.githubusercontent.com/900380/89504851-37e61000-d7b8-11ea-8209-5c232978a807.png)

Important info maybe contained in this screenshot: This looks like firefox to me.

**Comment by onli** [comment]
Okay, unlikely to make progress here (and it did not came up again). CKEditor also saw some updates anyway.
