### ISSUE TITLE
Multi-insert of images (generating a gallery) doesn't work with CKE

### ISSUE THREAD

**Issue by th-h** [s9y/Serendipity#705]
### Steps to reproduce:

* Activate WYSIWYg editor (tried with "Srendipity Standard").
* Start a new entry, insert two or more images simultaneously.

###  Expected result ...

... would be this code:

```
<ul class="s9y_gallery plainList">
<li class="s9y_gallery_item"><a class="serendipity_image_link" href="[...]"><!-- s9ymdb:10 --><img class="s9y_gallery_image" src="[...]" alt=""></a></li>
<li class="s9y_gallery_item"><a class="serendipity_image_link" href="[...]"><!-- s9ymdb:9 --><img class="s9y_gallery_image" src="[...]" alt=""></a></li>
</ul>
```

### Actual result ...

... is this code:

```
<ul>
<li><a class="serendipity_image_link" href="[...]"><!-- s9ymdb:10 --><img class="s9y_gallery_image" src="[...]" alt=""></a></li>
<li><a class="serendipity_image_link" href="[...]"><!-- s9ymdb:9 --><img class="s9y_gallery_image" src="[...]" alt=""></a></li>
</ul>
```

We miss the classes for `<ul>` and `<li>`.

Tested on 2.3.5 and current master.

**Comment by th-h** [comment]
@onli, could you have a look at that?

**Comment by onli** [comment]
@th-h Yes.

So, ckeditor has this advanced content filtering feature where it strips out everything but raw HTML if not configured otherwise. I tried configuring it to leave these classes, but failed, it happily continued stripping those classes out. I think it's time to disable this feature. I will prepare a PR, so this can be discussed, maybe someone is aware of a reason why not to this - this feels like something I would have done years ago.
