### ISSUE TITLE
[serendipity_plugin_categories] number of entries doesn't show

### ISSUE THREAD

**Issue by Zugschlus** [s9y/Serendipity#726]
Hi,

after flipping the switch "Show number of entries per category?" in the categories plugin to "Yes" and reloading the blog, nothing changed. I'd have expected a number of entries to show up.

Greetings
Marc

![Screenshot_20200504_185824](https://user-images.githubusercontent.com/1712376/80992654-21878b80-8e3a-11ea-85db-51d2179cfdf6.png)

![Screenshot_20200504_185844](https://user-images.githubusercontent.com/1712376/80992671-26e4d600-8e3a-11ea-83f3-82a204506cbf.png)

**Comment by onli** [comment]
Strangely enough that works for me in my dev blog with the current git master version. 

Which version of the plugin is that? Is it possible that this was a cache issue and is fixed by now?

**Comment by Zugschlus** [comment]
At the moment, i see the number of entries that have been written since my blog was moved to the new platform. Does the plugin get its information from a database table? Which one? Is there any way t re-create this table or should I fiddle around manually?

**Comment by th-h** [comment]
> Does the plugin get its information from a database table? Which one?

The `category` table holds the categories, the `entries` table your posts, and the `entrycat` is a mapping of the two. Every post that has a category needs an entry there; if it has more than one, it needs more than one entry.

If you moved all three tables, everything should just work. If post ids (from `entries`) or category ids (from `category`) changed, they must change in `entrycat`  accordingly.

> Is there any way t re-create this table or should I fiddle around manually?

As the table holds the mappings between entries and categories, there is no way to recreate it automatically. Please have a look at the table (or at your older posts: do they have categories yet?). If the `entrycat` table wasn't copied over, you just need to merge the table from your old installation with that of your new one. If the category ids do not match, because your categories in the new installation do have other ids than in the old one, that could be fixed (semi-)automatically, I think.

**Comment by Zugschlus** [comment]
Indeed, all categories are gone for the older blog entries. Please close this issue, this is obviously a local database thing.

**Comment by onli** [comment]
Okay :)

**Comment by Zugschlus** [comment]
The entrycat table was indeed emtpy, must have been mangled in translation. Only line in the dump that I imported was:

COPY public.s9y_entrycat (entryid, categoryid) FROM stdin;

whatever that might been.

I found the contents in an old backup and poked it into the database, display is now fine. Thanks for helping.
