### ISSUE TITLE
Trackback/Pingback and TLS on port 80

### ISSUE THREAD

**Issue by th** [s9y/Serendipity#764]
The s9y blog https://netz-rettung-recht.de/archives/2276-Wellenreiten-112020.html sends a trackback/pingback to the Wordpress blog https://www.thomas-huehn.de/2020/11/vom-gatter-zum-computer/

It doesn't work (the pingback you can see in the article has been added manually using curl).

Apart from lots of other things that could be wrong on either side, it seems that s9y is connecting to port 80, although the xmlrpc URL uses https.

On the s9y side:
> Überprüfe https://www.thomas-huehn.de/2020/11/vom-gatter-zum-computer/ auf mögliche Trackbacks ...
> • Kein Trackback: Konnte Verbindung zu www.thomas-huehn.de auf Port 80 nicht herstellen.

In the \<head\> of the target post (Wordpress):
> \<link rel="pingback" href="https://www.thomas-huehn.de/xmlrpc.php">

Does that behaviour look okay to the experts? I would have expected a connection to port 443.

(Pinging @th-h for reference).

**Comment by onli** [comment]
Thanks for this excellent report. Right, that s9y even tries port 80 there should be a bug.

The error might be at https://github.com/s9y/Serendipity/blob/8d1dd2994c8bdabfd735cfc67f0a5e8f3f1b2ea2/include/functions_trackbacks.inc.php#L125, where s9y sets port 80. On the other hand, why would it enter that code path for a https url? And why is port 80 ever set manually, won't the default be right? I assume that code has grown to be simply wrong and we should correct it. I will test it with my wordpress development blog.

Side note: Your wordpress theme should emit the RDF tags or a trackack meta tag instead, so that s9y can send it a trackback. Trackbacks look nicer and are more reliable. Last time I checked this wordpress still supported Trackbacks properly, but Themes had the habit of removing the needed tags. Might also be caused by the html minimization. Of course, this does in no way invalidate the bug.

**Comment by th** [comment]
Yes, indeed: Wordpress-Trackbacktest | John Doe’s personal blog

Haven't had luck with getting my Wordpress to emit those Trackback RDF tags, so far. My understanding was, that pingbacks were preferred, because the spamming potential is lower, since no "text" is transmitted and shown, just a sender and a link, but I guess you were referring to the whole xmlrpc security angle?

**Comment by onli** [comment]
The "pingbacks don't show texts" is more a convention. Since the page is downloaded anyway to check for the link the receiver could easily show the page title for example. But it's absolutely possibly that was claimed.

https://developer.wordpress.org/reference/functions/trackback_rdf/ should be the function you need, probably something to add to the part of your theme that emits the comments.

Are you okay with me marking this issue as solved? If it turns out that after the next upgrade, @th-h or some other s9y-blogger still can not properly send pingbacks to your blog you or said blogger can always re-open here.

**Comment by th** [comment]
Sure, it's solved.
