### ISSUE TITLE
Duplicate permalink because of sanitisation

### ISSUE THREAD

**Issue by mbirth** [s9y/Serendipity#777]
Similar to #738 I usually blog in English but also - rarely - in German. Instead of messing around with multilanguage, I've decided to just add a flag emoji (🇩🇪) to the title for those few German entries. E.g.

* Awesome Product
* Awesome Product 🇩🇪

Also, I don't want to bother users with the entry id, so I configured my permalinks to be `/article/YYYY-MM-DD-%lowertitle%.html`.

However, those emojis get stripped away when generating the permalink so both entries end up with the same permalink `/article/2020-02-02-awesome-product.html`. When opening the URL, the first result from the database wins - so depending on which entry I made first, visitors will ALWAYS see the English or the German version. There's no way for users to get the other.

I think there should be some check for collision and if so, the permalink should be made unique again - e.g. by adding `-1` to the end or similar. (Also, there maybe should be a `UNIQUE` constraint on the database table's field to make it impossible for such collisions to be added.)

Another way would be to make the sanitisation routine Unicode-aware. The flag emoji is composed of 2 [Regional Indicator Symbols](https://en.wikipedia.org/wiki/Regional_indicator_symbol), i.e. the special letters 🇩 and 🇪, and could be turned into the actual letters "DE".

**Comment by onli** [comment]
> Another way would be to make the sanitisation routine Unicode-aware. The flag emoji is composed of 2 Regional Indicator Symbols, i.e. the special letters 🇩 and 🇪, and could be turned into the actual letters "DE".

That sounds very reasonable to me. It should even not collide with most other blogs, because those usually identify entries by their id.

I'm not very familiar with that part of the code, but at first look I'd assume https://github.com/s9y/Serendipity/blob/d79ea2742235f1410965b4bc45108c60de3f9ef7/include/functions_permalinks.inc.php#L17 would need to be extended. Maybe it's something you could try out?

> Also, I don't want to bother users with the entry id, so I configured my permalinks to be `/article/YYYY-MM-DD-%lowertitle%.html.`

I understand the motivation, but I think that's a mistake. I'm even surprised it works at all. The routing seemed to assume the id is there, at least it's the expected codepath. And it avoids issues like this.
