### ISSUE TITLE
Serendipity 2.4.0 version does not work on PHP 7.0

### ISSUE THREAD

**Issue by jameswill** [s9y/Serendipity#794]
Hi,

I tried installing serendipity 2.4.0 version on my server with PHP 7.0 and Mysql 5.5

As the requirement page on the website states PHP 7.0 https://docs.s9y.org/docs/users/getting-started/fresh-installation.html

However on the last page of the installation (on redirecting "serendipity_admin.php" ) it gives following error.

**_Uncaught Error: Call to undefined function array_key_first() in [[PATH]]/serendipity240/include/functions_installer.inc.php:909_**

array_key_first() function requires minimum PHP 7.3 to operate. https://www.php.net/manual/en/function.array-key-first.php 

Is the requirement has been changed ?

**Comment by stevleibelt** [comment]
Hello @jameswill,

PHP 7.4 has an end of life in [6 days](https://www.php.net/supported-versions.php). This is the last supported 7.x-Version of PHP.

I bet your linked [documentation](https://www.php.net/supported-versions.php) page will get an update.

A friendly reminder, because of the end of life of php 7.4, you should plan to upgrade your server setup.

Best regards,
Stev
