### ISSUE TITLE
Net_DNS2 from 2.4.0 is not compatible with PHP8

### ISSUE THREAD

**Issue by manitu-opensource** [s9y/Serendipity#805]
The Net_DNS2 version bundled with 2.4.0 is not (fully) compatible with PHP8.

Especially using the `each` function (line 923, bundled-libs/Net/DNS2.php) is no longer supported in PHP8.

We suggest to use a newer version from upstream (https://github.com/mikepultz/netdns2/blob/master/Net/DNS2.php)

**Comment by onli** [comment]
Hey, thanks for the report. And I'm sorry you ran into this.

Using the newer version looks like a good solution, we just have to check it again :)

**Comment by onli** [comment]
Hi @manitu-opensource 

Looking at this dependency, I see no usage of it in the core or in any of the published additional plugins. Do you use or did you see a specific usage of Net_DNS2 with serendipity?

I'm asking so I can test this upgrade. And also, since ideally I'd like to let composer manage this dependency, but then the path would change -> if it's used the old require path should continue to work, but that's a bit hairy because of the other dependencies under bundled_libs/Net. But if there is no real usage of this I'd be okay with making this a breaking change.

**Comment by onli** [comment]
In my test, https://github.com/s9y/Serendipity/commit/e16533863e198a4ec3bfc45e354de8a135e02065 solved this issue. Upgrade of the dependency as proposed, plus moving it to composer, with a symlink to keep DNSBL working.

**Comment by hannob** [comment]
Can we close this bug?

**Comment by onli** [comment]
I'd say so. Please re-open if something has gone wrong with this fix.
