### ISSUE TITLE
Installer/upgrade messages emitted by serendipity_die()

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#89]
In [a comment](https://github.com/s9y/Serendipity/issues/80#issuecomment-37011301) in #80, @ophian pointed out that the error messages generated by `serendipity_die()` could have better (rudimentary) markup and possibly (basic inline) CSS.

I would also like to add that these seem to be emitted in the wrong place at least in the upgrader's final step. They are emitted *before* the `<header>` (or even before `<head>`?!) when they really should be emitted at the beginning of `#content` if possible.

(I though this was worth a seperate issue.)

**Comment by garvinhicking** [comment]
We could simply have a parameter like $use_framework that we set to TRUE when using serendipity_die() not for a fatal error, but for the upgrade notice? We'd still need hardcoded HTML/CSS for that output, since we cannot rely on using the Smarty output of a template (due to needed upgrade). But we should be able to make a better look of the output message, with minimal CSS effort...?

Any takers? :-)

**Comment by yellowled** [comment]
It should be possible to just use the `.msg_error` class from 2k11's admin for this (as inline CSS):
```
.msg_notice {
    display: block;
    margin: 1.5em 0;
    padding: .5em;
    background: #f2dede;
    border: 1px solid #e4b9b9;
    color: #b94a48;
}
```

and then wrap each of theses message in `<div class="msg_notice"></div>`.

**Comment by onli** [comment]
Rudimentary, that can be extended later, but it did not seem like that would happen by itself ;)
